### ISSUE TITLE
messaging-app does not have a maintainer

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/messaging-app#1]
No one is currently maintaining this app. If you would like to become the maintainer, please reply to this issue or get a hold of us via another method.

The app maintainers will be responsible for coordinating the following (doing it yourself is still coordinating, if you prefer that):

* Triaging bugs
* Fixing bugs
* Vetting and implementing enhancement requests
* Corresponding with the UBports project regarding the app's progress
* Requesting bounties be posted for the app
* Using SMS and MMS more than the average person

**Comment by Benni777** [comment]
> No one is currently maintaining this app. If you would like to become the maintainer, please reply to this issue or get a hold of us via another method.
> The app maintainers will be responsible for coordinating the following (doing it yourself is still coordinating, if you prefer that):
> 
> Triaging bugs
> Fixing bugs
> Vetting and implementing enhancement requests
> Corresponding with the UBports project regarding the app's progress
> Requesting bounties be posted for the app
> Using SMS and MMS more than the average person

Hello, 
I would try to support at maintaining this app.

Regards

**Comment by UniversalSuperBox** [comment]
Hi @Benni777,

That sounds great! You can get started by forking this repository and taking on any of the bugs you see fit, then sending a pull request. I'll be sure to watch for any notifications to help you get any changes pulled in.

If you have any questions about getting your development environment set up, just let me know!

**Comment by Benni777** [comment]
Currently I review the code to get an overview and investigate the QML language because until now I have no experience.

Next week I have one week of vacation, there I will also setup the development environment.

Could we use this Issue to discuss about setup of the development environment?

**Comment by UniversalSuperBox** [comment]
Of course, whatever you need

**Comment by UniversalSuperBox** [comment]
There are now maintainers of Messaging-app. :)
