### ISSUE TITLE
Message thread title bar content varies randomly

### ISSUE THREAD

**Issue by abkro** [ubports/messaging-app#100]
Device: Nexus 5
Release: 16.04 (2019-W21)
Channel: rc

Expected behavior:

Open messaging app. Open message thread. Title bar should show the name of the recipient (if one exists in the address book)

Actual behavior: 

Title bar sometimes shows the name of the recipient, sometimes shows the phone number. There is no obvious pattern to when the one or the other is displayed. Exiting to the main view and re-entering a message thread after seeing only the phone number at the top of the page produces the corresponding name.

**Comment by krille-chan** [comment]
Thank you for your bug report but this seems to be a duplication of #77

**Comment by abkro** [comment]
Indeed!

I obviously didn't check well enough before posting. Sorry!

Ari


On Fri, 24 May 2019 07:36:10 -0700, Christian wrote:
> Thank you for your bug report but this seems to be a duplication of #77 
>

-- 
Vennlig hilsen,
Ari Börde Kröyer

Sendt med Dekko fra min Ubuntu mobil
www.ubports.com
