### ISSUE TITLE
Message threads overlap in main window when using external display

### ISSUE THREAD

**Issue by abkro** [ubports/messaging-app#105]
**Expected behavior:**
Either:
Connect device to external display. Start messaging app. App opens with main window in left pane of window on screen and selected message thread in right pane. All message threads listed in left pane.

Or:
Connect device to external display with message app already running. App is displayed in window on screen with main window in left pane  and selected message thread in right pane. All message threads listed in left pane.

**Actual behavior:**
In both cases above, the left pane shows all threads, but the top two (most recent ones) overlap at first, making it impossible to read them properly (first screenshot below). Clicking on them causes the window to refresh and display them correctly (second screenshot below)

**Steps to reproduce:**
1. Connect to external display.
2. Open message app.

or

1. Open message app on device.
2. Connect to external display.

**Device**: Nexus 5
**Channel**: rc
**Release**: 2019-W22

![screenshot20190601_102142612](https://user-images.githubusercontent.com/7359038/58761200-d5eda300-8541-11e9-833b-bf4bee901611.png)
![screenshot20190601_102735018](https://user-images.githubusercontent.com/7359038/58761212-f4539e80-8541-11e9-836c-5def8de8b7de.png)

**Comment by krille-chan** [comment]
thank you for the bug report. I guess this is a problem of the Ubuntu UI toolkit. When we finish a newer version, this should ne fixed.

**Comment by lduboeuf** [comment]
can someone test it again ?

**Comment by lduboeuf** [comment]
( on devel )

**Comment by lduboeuf** [comment]
@abkro are you still experiencing that issue ?

**Comment by abkro** [comment]
Will check and report.

**Comment by lduboeuf** [comment]
@abkro no news ?

**Comment by abkro** [comment]
So sorry! I forgot to follow this up. I am on a trip now, but I have my device and should manage to check some time this weekend...

**Comment by abkro** [comment]
I finally got the chance to check this. On my N5 now running OTA-13 it works normally. There is a scaling issue, but I am not seeing the overlap that I previously saw.

**Comment by lduboeuf** [comment]
thanks for your feedback. So we can close it  @Flohack74
