### ISSUE TITLE
messages are duplicated

### ISSUE THREAD

**Issue by cyberpunkedu** [ubports/messaging-app#108]
Device: mako
Channel: devel
Build: 2019-06-04
![screenshot20190604_172122695](https://user-images.githubusercontent.com/3128635/58922021-02deb900-86ee-11e9-9cfd-8eebe1f4ebe3.png)

Type a message and send. Duplicate message happens.

Could be keyboard issue as last message shows in typing area...

**Comment by krille-chan** [comment]
This could be caused by my latest fix. I will fix this too

**Comment by krille-chan** [comment]
Very strange. The complete chat page reloads after sending. This makes the textfield restoring the last message from the cache.

**Comment by StefWe** [comment]
Looks good to me
Tested on mx4

**Comment by cyberpunkedu** [comment]
This is still happening on the latest devel images.
It happens when you leave the messaging app, and then go back to an old conversation. You will find a "pre-typed" message in the input field.

**Comment by krille-chan** [comment]
> This is still happening on the latest devel images.
> It happens when you leave the messaging app, and then go back to an old conversation. You will find a "pre-typed" message in the input field.

This is how it should work. Bug would be if the pre-typed message is a message which is already sent. Is it?

**Comment by cyberpunkedu** [comment]
> > This is still happening on the latest devel images.
> > It happens when you leave the messaging app, and then go back to an old conversation. You will find a "pre-typed" message in the input field.
> 
> This is how it should work. Bug would be if the pre-typed message is a message which is already sent. Is it?

Yes, it has a pre-type message from the previous message that I sent already.
