### ISSUE TITLE
Some longer texts extend outside of the text bubble

### ISSUE THREAD

**Issue by dieharddan** [ubports/messaging-app#110]
Hello, sometimes when receiving texts, the text will extend outside the text bubble and will become partly unreadable. I am using a OPO device

![text](https://user-images.githubusercontent.com/51171015/59049410-8531bf00-884d-11e9-9577-2dc9335e4b10.png)

**Comment by krille-chan** [comment]
Thank you for the report. This issue mostly occurs in convergence mode and is affecting other apps like fluffychat or telegram too sometimes. We need to find a better way to calculate the label width. Maybe a new toolkit can help with this task @bhdouglass ?

**Comment by bhdouglass** [comment]
Looks like a word wrapping issue, unless I'm missing something @ChristianPauly ?

**Comment by Flohack74** [comment]
You need a hidden rendering, then measuring, then text box sizing function like in TELEports or the old Telegram app...

**Comment by krille-chan** [comment]
> You need a hidden rendering, then measuring, then text box sizing function like in TELEports or the old Telegram app...

Okay, so here we have the width calculation in messages app: https://github.com/ubports/messaging-app/blob/xenial/src/qml/MessageBubble.qml#L114-L119

And here in (old) Telegram using an invisible Label with the same text for width calculation: https://github.com/ubports/telegram-app/blob/master/telegram/app/qml/components/MessagesListItem.qml#L278
Looks a little bit hacky but seems to work better. We should adapt the Telegram solution to fix this ;)

**Comment by bhdouglass** [comment]
Would TextMetrics help here? https://doc.qt.io/qt-5/qml-qtquick-textmetrics.html

**Comment by Flohack74** [comment]
Not to forget that in Telegram we need support for text formatting, while messaging app just has plain text, maybe thats the difference.

**Comment by Flohack74** [comment]
Got this now also with an MMS:
![grafik](https://user-images.githubusercontent.com/16186470/62042901-76d5a300-b1ff-11e9-9f34-100bc830a2e1.png)

**Comment by ntorquet** [comment]
My wife and I have the same issue with mms. She had an OPO and me a bq E5-HD Ubuntu Edition.
Another very strange mms behavior, but this time only on my wife's OPO: sometime, she received new sms mixed with old sms. That is crazy! But probably not the same issue?

**Comment by UniversalSuperBox** [comment]
Closed by #130

**Comment by gbdomubpkm** [comment]
For me, Seen today on BQ E5 HD dev v 488, the bug is back :
![SMS out of box](https://user-images.githubusercontent.com/50362604/77794481-42570700-706c-11ea-9944-2749fcd472f5.png)

**Comment by lduboeuf** [comment]
can you please open a new ticket, but i can't confirm on N5 with today image on devel

**Comment by gbdomubpkm** [comment]
OK.
Just seen tonight.
But anyway, it's a bug that's always happened randomly to me.
