### ISSUE TITLE
Can't receive group texts from iphones

### ISSUE THREAD

**Issue by dieharddan** [ubports/messaging-app#111]
Hello, I am unable to receive group texts if it is being sent from an iphone. Group texts from android work perfect. I thought I read that apple routes their texts through their servers, so i don't know if that is part of the issue but if I put the sim in my android device, I can again receive iphone group texts

**Comment by krille-chan** [comment]
Thank you very much for your report.

Do you know whether this are sms or mms group texts? And on the iPhone is the message bubble green or blue? Blue means that the message is sent through the iMessage messaging service which only an iPhone can receive.

**Comment by dieharddan** [comment]
My android phone shows that they are mms and the messages on the iphone are green

**Comment by krille-chan** [comment]
Okay thank you. So I guess this is related to the mms bug.

**Comment by dieharddan** [comment]
which mms bug? Also, i'm not sure if it matters, but i'm also receiving a bunch of texts from "x-ofono-unknown" which it appears to be weird info from my carrier like servers and ports

**Comment by jfrederickson** [comment]
Referring to this one, probably: https://github.com/ubports/ubuntu-touch/issues/12

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/111

Sorry for your inconvenience.
