### ISSUE TITLE
Overview of MMS partially hidden by OSK

### ISSUE THREAD

**Issue by ghost** [ubports/messaging-app#121]
Detected with FP2 OTA 9 stable.

Step to reproduce:
Open a message with a picture sent through MMS.
Tap on the picture to get an overview on full screen.
The picture is partially hidden by the OSK, there is no way to remove the keyboard.
The only way to see the full picture is to download it (feasible, but few extra steps).

Behavior expected:
the keyboard is automatically hided in case of MMS overview and reappear when back to massage page.

**Comment by gwado** [comment]
True !
But you can swipe the keyboard with one finger on the top of the keyboard (in the margin top).

**Comment by ghost** [comment]
Interesting! I was not aware of this workaround.
However, I still think the keyboard should be automatically hided by default.

**Comment by gwado** [comment]
> Interesting! I was not aware of this workaround.
> However, I still think the keyboard should be automatically hided by default.

True. I found this by chance.
I can suppose we can hide the keyboard before open the picture. I will see in the next few days.

**Comment by lduboeuf** [comment]
@Flohack74 this bug is fixed with https://github.com/ubports/messaging-app/pull/166
