### ISSUE TITLE
Draft SMS is erased when closing the App.

### ISSUE THREAD

**Issue by Thieb67k** [ubports/messaging-app#124]
When I write a text within a conversation and quit the conversation using the back-arrow, I find my text saved. Same thing if I quit the conversation then close the App: when I re-open the App and go back to the conversation, I find the text saved.
That is what we expect.

But, if I bypass the back-arrow and close the app, the text is erased.
(on nexus 4, mako, OTA-10)
I would say that is a bug according to other users. --> UPDATE: That bypass bug is clearly random and not happening for days...

But the text below is still a possible improvement:

Additionnaly, would it be nice to allow users to create a draft without a pre-existing conversation (not possible to me)? And the possibility to have the "To:" field empty, in the aim to complete it afterwards?
Because sometimes I want to prepare a text and sent it several hours later (when I prepare an event) and now I do not have possibility to intercalate a text between an opened conversation and a draft.

So far, I should open a conversation with myself then copy/paste or forward the text to the complete list of adressees just before sending.

I hope I am clear... 
Anyway, thanks for the job!

_Originally posted by @Thieb67k in https://github.com/ubports/messaging-app/issues/65#issuecomment-523775355_

**Comment by lduboeuf** [comment]
@Thieb67k could not reproduce for the draft not beeing saved (N5 devel). You should create another ticket ( and so close that one if fixed ) for your improvement request

**Comment by lduboeuf** [comment]
last works on devel seems to fix that, can you close that issue ? cc @Flohack74
