### ISSUE TITLE
No notification push when group texts are received. 

### ISSUE THREAD

**Issue by parksjr** [ubports/messaging-app#125]
**Expected behavior:**
New notification sound, and in top drawer when group mms is received.

**Actual behavior:**
No notification when group mms received, no sound, and no green new message indicator. I can unlock my phone and open the messages app and see the new notification badge on a conversation since the last time I looked at the phone.

**Steps to reproduce:**
1. open messaging-app
1. click the plus button at the top right of the messages screen to start a new conversation.
1. click the double meeple icon to the right of the to box to create new mms group
1. add at least two members
1. send message
1. receive response

**Device Information**
Device: Nexus 5
Channel: Development
Release: 2019-08-21/2

**more info**
i mentioned this in a comment on the "Cant receive MMS" issue:
https://github.com/ubports/ubuntu-touch/issues/12#issuecomment-524388654

**Comment by krille-chan** [comment]
MMS is not working for me at all. Can someone confirm this who is able to send MMS?

**Comment by parksjr** [comment]
@ChristianPauly if there are specific log files i can parse through and attach while I reproduce this on my device, let me know which logs to best look at and I will attach the relevant lines in here.

**Comment by lduboeuf** [comment]
@parksjr still experiencing that ?

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/125

Sorry for your inconvenience.
