### ISSUE TITLE
SMS-->Event conversion?

### ISSUE THREAD

**Issue by Thieb67k** [ubports/messaging-app#126]
Hello,

Is it possible to make the conversion of a SMS into event, in calendar, possible? 
Best.

**Comment by UniversalSuperBox** [comment]
Doing this would require scanning text messages to find dates and invitations in many different languages and styles. Google does this by sending your messages to their servers. Apple probably has many developers on the case.

It isn't an impossible problem to solve, but it is very improbable.

**Comment by Thieb67k** [comment]
Ok,
Thanks for the answer.
And what if we make it easier: creating an event shortcut into messaging app that automatically open an empty event form with Calendar. With no scanning intrusive step that noone wants.
The user must add info by himself.
But I agree that if the opened event form is empty, that would be considerate like an "incomplete" function...

**Comment by UniversalSuperBox** [comment]
Then we should also create a shortcut to create any number of things that someone could want to make after reading a text message, like a too or note in Notes. I don't quite see that being needed. You can always swipe down from the upper right and go straight to the Calendar by tapping on today's date above the mini calendar.
