### ISSUE TITLE
Text MMS cant be read

### ISSUE THREAD

**Issue by gwado** [ubports/messaging-app#128]
Hello,

I cant read a mms with only text and i cant swipe for options too.
But if someone comes before me... :)
![image](https://user-images.githubusercontent.com/54929707/64317113-0157b200-cfb7-11e9-982f-4c81b1a12c42.png)

**Comment by parksjr** [comment]
I experience the same two issues reported here.

Device: Nexus5 (hammerhead)
Devel channel

When chatting in a group text, received text messages are MMS and the text is attached as plain/text format. Maybe there is a way to attach as html so it adheres to the parent container width, but I have not gotten that far with this yet.

Also, the swipeLocked attribute in AttachementsDelegate.qml line 36,  loops through attachmentsView.children and checks if (attachmentsView.children[i].item && !attachmentsView.children[i].item.swipeLocked). this is where it sets swipeLocked: true on all group messages received. 

I've removed this check (force swipeLocked: false) to test if I can swipe, and it works, but I have not studied enough in here to know why this conditional loop is here, and what else it may impact.

Maybe a more seasoned UT developer has some insight, but until then I am still figuring things out as best I can. And I hope to contribute more soon.

**Comment by gwado** [comment]
When the message in question is displayed in summary (in the list of conversations, for example, or in notification), there is a line break.
The text is normally truncated. But we could use the same line break system.

I just don't have enough time to look at the code in more detail. The weekend is coming...

**Comment by gwado** [comment]
> I experience the same two issues reported here.
> 
> Device: Nexus5 (hammerhead)
> Devel channel
> 
> When chatting in a group text, received text messages are MMS and the text is attached as plain/text format. Maybe there is a way to attach as html so it adheres to the parent container width, but I have not gotten that far with this yet.
> 
> Also, the swipeLocked attribute in AttachementsDelegate.qml line 36, loops through attachmentsView.children and checks if (attachmentsView.children[i].item && !attachmentsView.children[i].item.swipeLocked). this is where it sets swipeLocked: true on all group messages received.
> 
> I've removed this check (force swipeLocked: false) to test if I can swipe, and it works, but I have not studied enough in here to know why this conditional loop is here, and what else it may impact.
> 
> Maybe a more seasoned UT developer has some insight, but until then I am still figuring things out as best I can. And I hope to contribute more soon.

If I return true for both conditions, it doesn't work anymore.

**Comment by gwado** [comment]
> I experience the same two issues reported here.
> 
> Device: Nexus5 (hammerhead)
> Devel channel
> 
> When chatting in a group text, received text messages are MMS and the text is attached as plain/text format. Maybe there is a way to attach as html so it adheres to the parent container width, but I have not gotten that far with this yet.
> 
> Also, the swipeLocked attribute in AttachementsDelegate.qml line 36, loops through attachmentsView.children and checks if (attachmentsView.children[i].item && !attachmentsView.children[i].item.swipeLocked). this is where it sets swipeLocked: true on all group messages received.
> 
> I've removed this check (force swipeLocked: false) to test if I can swipe, and it works, but I have not studied enough in here to know why this conditional loop is here, and what else it may impact.
> 
> Maybe a more seasoned UT developer has some insight, but until then I am still figuring things out as best I can. And I hope to contribute more soon.

This is the first part of the solution. If i return true both conditions, we can swipe !
The problem, now, is to format correctly the break lines.
In messagingapplication.cpp (line 310) if i text.replace(" ", "\n"), i can see all text. But it's not okay yet because there's a line break for each word....
I'm searching. I dont know c++

**Comment by gwado** [comment]
I'm moving on....
All data is read from qml files. Only MMS messages (plain text) are read in Qt/C++ and returned to a QML file.
That's where i think there's a problem.
Either the text file is misread or returned incorrectly. I'm missing a function that would allow me to tell QML that the text returned by C++ is a pure "text".
I don't know if i'm clear.
I don't know if i'm on the right way.

**Comment by gwado** [comment]
Then it can come from the parseText() function (messagebubbles.qml:60) which does not go around the text in question.
For example, it doesn't close the div that it opened.
Strange.

**Comment by gwado** [comment]
It's ok. It's just a problem of width. I'll make a correction proposal soon.
MessageBubble.qml:147, must be :
`Component.onCompleted: width = maxDelegateWidth`


There's still that deactivated swipe problem you're stating.
We have a workaround, we have to set it to false.
But I still don't fully understand this part of the code. I'm not making a proposal yet.

**Comment by parksjr** [comment]
I was trying to look into the messageText last night but i kept going in circles between MessageBubble.qml to MessageDelegate.qml to AttachmentsDelegate.qml. I look forward to your proposal on it maybe it will help me understand better. 

I have a proposal for the swipe locked property, basically reversing the conditional so that swipe is enabled by default unless an attachment item specifies other wise.

**Comment by UniversalSuperBox** [comment]
Closed by #130
