### ISSUE TITLE
Touch on new sms notification behaviour

### ISSUE THREAD

**Issue by mihaelmilea** [ubports/messaging-app#13]
For the sake of having the same behaviour with all the notifications, could we have that when we touch a sms notification it will launch the messaging app instead of the "quick-answer to the sms"? - and, of course, have the quick-answer open when we touch the icon on the right of the notification - which as of now launches the messaging app.

I say for the sake of having the same behaviour because for example, when we touch a notification about a new email, it opens Dekko.

**Comment by lduboeuf** [comment]
i don't know if we have a common UX for notifications, i personnaly prefer the messaging notification behavior

**Comment by cibersheep** [comment]
If you type on the icon of the notification it will open Messagin app

**Comment by Keneda-ut** [comment]
> If you type on the icon of the notification it will open Messagin app

He's right, touching message icon on the right of notification opens messaging app.
MX4, OTA11 stable

**Comment by Flohack74** [comment]
So can we close it?

**Comment by cibersheep** [comment]
I think so, yes
