### ISSUE TITLE
multiselect operations in threads(conversations) are behaving strangely

### ISSUE THREAD

**Issue by matv1** [ubports/messaging-app#131]
Device Meizu Pro 5
channel RC 2019-W33/2

Operation: 
- Longpress a conversation to enable multiselect
- Select, then deselect, more then one thread in a place downward in the conversations list (away from immediate view)
- scroll back up, then down again to the same items

result is that the messages are again selected.

**Comment by matv1** [comment]
Also, after troubleshooting this on TG with a couple of people, it has been reported that when multiple conversations are selected, after deleting, not all selected conversations actually do get deleted. This sounds very much related but others need to confirm this as I havnt been able to.

**Comment by Danfro** [comment]
I can confirm this issue on my E5, running RC.

Select two conversations. Scroll up a few pages. Scroll down again. The very last conversation is selected and all exept of the lowest conversation of the ones selected before are unselected.

**Comment by Thieb67k** [comment]
Hello,
I noticed that on LG Nexus4 OTA-5-->10, stable channel.
I reported a strange behaviour similiar to that opened issue, in issue #28 (Selecting messages in thread for mass operation #28).
Best,
