### ISSUE TITLE
Messaging app retaining input text after sending SMS

### ISSUE THREAD

**Issue by james-lyon** [ubports/messaging-app#136]
- Device: BQ Aquaris E4.5
- Channel: Stable
- Build: OTA-10

### Steps to reproduce
I'm still trying to find out how to reliably reproduce this bug, I will update the report if I work it out. I'm hoping someone else has seen the same behaviour...

### Expected behavior
After sending an SMS, the text input field should be empty.

### Actual behavior
On some occasions, after sending an SMS, I will receive a reply, and upon reopening the Messaging app my initial message will be shown in the text input field - as if my message hadn't been sent. I then have to delete the text before I can enter a new message.

Even leaving the message conversation and restarting the messaging app does not delete the text from the input field.

I never encountered this behaviour before updating to OTA-10

**Comment by Thieb67k** [comment]
Happened to me as well on LG Nexus4.

**Comment by james-lyon** [comment]
I am encountering this bug more and more frequently now. This and other Messaging app bugs (keyboard disappearing, screen scrolling up randomly) are close to making me abandon UT.

**Comment by ateliernz** [comment]
confirmed on FP2 OTA-11

**Comment by lduboeuf** [comment]
I don't have that issue since a while ( i'm on devel )

**Comment by dbdb78** [comment]
confirmed on N5, but not the last sms sent - but the one before my last.

This occured for me as I had a missed called from the same person who I was about message.

**Comment by lduboeuf** [comment]
@james-lyon are you still experiencing that ?, the "maybe-fixed" is merged now for devel

**Comment by james-lyon** [comment]
I'm still on stable, so I'm still experiencing the bug, but possibly less frequently than before...

**Comment by lduboeuf** [comment]
last works on devel seems to fix that, can you close that issue ? cc @Flohack74
