### ISSUE TITLE
is IRC Chat related code still accurate ?

### ISSUE THREAD

**Issue by lduboeuf** [ubports/messaging-app#142]
I was looking at the code and i've found lots of IRC features, is it still accurate or can we start cleaning the code ?
So hard to get into Messages.qml

**Comment by krille-chan** [comment]
@Flohack74 said we can start cleaning this. But it will be hard to make sure that this will not create new bugs

**Comment by Flohack74** [comment]
Currently there are no plans to blow up messaging-app into an IRC client. So feel free ^^

**Comment by lduboeuf** [comment]
Fine, but i'm not very familiar with all the features now, better if someone can clean it

**Comment by lduboeuf** [comment]
Can someone please tell me what ChatEntry is ?

**Comment by lduboeuf** [comment]
I see it comes from telephony service, and used everywhere but i don't get what is is for

**Comment by krille-chan** [comment]
Can't tell you what this is. But for me it looks like that the Messages app was intended to become a multi-protocol messenger like Pidgin. Maybe we could still use these chat features when it comes to implementing RCS?

**Comment by lduboeuf** [comment]
Not sure if it is a good thing to keep it like this, it let lots of "if" statements in code and hard to extend/maintain.

**Comment by lduboeuf** [comment]
oh ok ChaEntry, is an important part of the app, responsible for sending the message ... So we can't touch that :)

**Comment by lduboeuf** [comment]
> Maybe we could still use these chat features when it comes to implementing RCS?


IMO, for RCS we would rewrite it differently, here we chain too much if statements. I will give a try to to start removing IRC parts, let see. [EDIT] seems to be too early for me...

**Comment by lduboeuf** [comment]
After some times on the app, like @krillefear said we should keep all the multi protocol stuffs if one day RCS will come.
