### ISSUE TITLE
Use UbuntuShape instead of png for text bubbles?

### ISSUE THREAD

**Issue by cibersheep** [ubports/messaging-app#156]
Change the BorderImage for an UbuntuShape?

https://github.com/cibersheep/messaging-app/blob/xenial/src/qml/MessageBubble.qml#L105

**Comment by lduboeuf** [comment]
So since OTA-16, UbuntuShape is used instead of BorderImage. Can we close that issue @cibersheep ?

**Comment by cibersheep** [comment]
Is it? Coooool. Thanks for letting me know :*
I close it with a question: Any impact on performance?

**Comment by lduboeuf** [comment]
yes since Qt5.12, BorderImage had side effects, so just tried with UbuntuShape. I don't see any performance penalty

**Comment by cibersheep** [comment]
Lovely. Thanls
