### ISSUE TITLE
date not animated when deleting a thread

### ISSUE THREAD

**Issue by Danfro** [ubports/messaging-app#157]
When deleting a thread in messages list (main view), the content of the thread below the deleted thread is moved upwards with an animation - except of the date.

The date immediately jumps to the new position and overprints with the old date. I know it is there only for a split second, but it does look somehow weird.

**Comment by lduboeuf** [comment]
confirmed, that happens since my changes on Thread list, Got to figure out how to handle animations on sections and that overlapped date. But don"t know yet :)

**Comment by lduboeuf** [comment]
Related issue that lead to the same Qt Bug , see https://github.com/ubports/messaging-app/pull/174

**Comment by lduboeuf** [comment]
@Danfro can you confirm the fix ? It should be since https://github.com/ubports/messaging-app/pull/174 merge

**Comment by Danfro** [comment]
Yes, confirmed. This is now fixed. Thanks, missed that entirely. ;-)
