### ISSUE TITLE
List of conversations is broken when leaving a thread and it should jump to top

### ISSUE THREAD

**Issue by Flaburgan** [ubports/messaging-app#161]
Fairphone 2, last `devel` code. This is a regression since late december, if I remember correctly.

Here is a video of it (in gz, github doesn't allow upload of ogv files): [bug-sms.ogv.gz](https://github.com/ubports/messaging-app/files/4114623/bug-sms.ogv.gz)

It can be reproduced with a SMS from anybody but I have only one phone so here I did it with my own phone.

**Step to reproduce:**

- Open an SMS conversation **which is not the first one (the most recent)**
- Send a SMS and go back to the conversations list
- The conversation is now displayed above the "Today" title, hidden and unreachable

**Comment by lduboeuf** [comment]
can't reproduce for instance, can you confirm with last devel image ?

**Comment by Flaburgan** [comment]
Yes, I reproduce each time with the always last devel image. Simply answer the second conversation in your SMS list and quickly tap back after you sent it.

**Comment by lduboeuf** [comment]
works well on N5, just noticed when sms takes time to be sent, a white placeholder  and then filled when the sms is sent

**Comment by Flaburgan** [comment]
I can't be more descriptive than the video above :p do you think this is specific to the Fairphone 2?

**Comment by lduboeuf** [comment]
oh yes effectively :), you have also this blank placeholder but it does not appear like you above the "today" section

**Comment by lduboeuf** [comment]
I wonder what can cause that. Does it occurs on Stable ?. For me, it could be something with component not being destroyed well since it is blocked by the sending process, so UI ( the thread list )  is not refreshed

**Comment by Flaburgan** [comment]
The UI is refreshed, but the message is inserted at the wrong place.
It doesn't occur on stable and it was not there in devel after the unity merge, the regression appeared during the christmas holidays.

**Comment by lduboeuf** [comment]
yes seems related to the change in the component for the Thread List, it is maybe heavier to load. But it occurs only if message is not sent immediately.

**Comment by lduboeuf** [comment]
I had this today while working on a new feature. My database was messy, i did clean my db and seems to be okay-ish

**Comment by lduboeuf** [comment]
i see that it is due to `displaced` animation on the Thread List, i don't know yet how to get rid of it except by removing the animations.

**Comment by lduboeuf** [comment]
i have it almost everytime when testing with the draft rework https://github.com/ubports/messaging-app/pulls

**Comment by lduboeuf** [comment]
so after lots of investigation, i give up by removing animations on the Thread list, see PR #174
