### ISSUE TITLE
Messaging App Scroll Issue

### ISSUE THREAD

**Issue by lnoble237** [ubports/messaging-app#163]
- Device: FP2
- Channel:
- Build: 16.04

### Steps to reproduce
Open a conversion in Messaging app

### Expected behavior
Be prompted to write a new message in the message box, with the scroll bar at the very bottom of the conversion (showing the most recent message)

### Actual behavior
1) If I was the last person to send a text the message box contains my last sent text again (happens in most cases)
2) Scrolls to the top of the conversation or the middle of the conversion (happens in some of the cases)
3) Shows the expected behaviour described above (happens in some of the cases, especially if I was not the last person to send a message)

### Logfiles and additional information
http://paste.ubuntu.com/p/4dn8ghgWj9/

**Comment by lduboeuf** [comment]
@LDovic are you on devel channel ?

**Comment by LDovic** [comment]
erm I cant remember to be honest, how do I check that?

**Comment by lnoble237** [comment]
I cant remember which channel I used when I installed it. How do I check? I couldn't find it in the settings.

**Comment by lduboeuf** [comment]
Then you are probably on stable ( the default ). You can check this in settings-> updates ( or something similar ( it is in french for me ), and then see bottom options.
Your bugs seems to be fixed for OTA-12 ( not available on stable yet)

**Comment by lnoble237** [comment]
I get my updates from release candidate, other than that I cant tell which channel im on!

**Comment by lduboeuf** [comment]
so your on RC channel, modifications are not there yet, update in RC is about to land soon as i've heard

**Comment by LDovic** [comment]
thanks im not sure why i did the rc one, if i switch my updates to stable will that change the channel or do i need to reinstall?

**Comment by lnoble237** [comment]
ok cheers
