### ISSUE TITLE
SMS Undo / Redo Function

### ISSUE THREAD

**Issue by lnoble237** [ubports/messaging-app#165]
Device: FP2
Channel: RC
Build: 16.04

Problem:
When deleting a large chunk of text for an SMS (for example, a whole sentence) in the text field, the text deletes a bit too quickly, it's difficult to delete portions of the text. More often than not, you accidentally delete the whole text.

Solution 1:
Delete the text more slowly, character by character or just more slowly.

Solution 2:
A really great feature would be to have an undo / redo option for the SMS textfield.

**Comment by kugiigi** [comment]
The keyboard now has undo/redo function and I don't think we can really control how deletion works within the app to begin with. Perhaps we can close this @LDovic ?

**Comment by lnoble237** [comment]
@kugiigi  hi yeah with the multiple updates the os has received since this issue has disappeared, thanks!
