### ISSUE TITLE
Suru Dark colors 

### ISSUE THREAD

**Issue by josele13** [ubports/messaging-app#178]
**Issue description :** 

When you open the message you see the text and the phone number, the phone number has a dark blue color that is confused with the color of the theme Suru dark .

I send two screenshots, the left image is as it currently is and the right image is a color change option. 

in the right image you can see perfectly the number that comes from the message.

regards...
![Captura de pantalla -2020-03-15 20-46-39](https://user-images.githubusercontent.com/52839437/76709664-d89c3c00-6700-11ea-88c5-4cd516c56a47.png)

**Comment by lduboeuf** [comment]
probably an issue more to move in ubuntu-touch repo, as it is a global theming issue ( not sure, haven't look at he code )

**Comment by Flohack74** [comment]
@cibersheep can tell you what to do here ;)

**Comment by josele13** [comment]
in the photo on the right is the solution, put the light blue color that is used in other apps and that reads very well

**Comment by cibersheep** [comment]
Ouh, I forgot to look into this. Probably color hardcoded instead of theme palette
