### ISSUE TITLE
Add sent time in SMS info

### ISSUE THREAD

**Issue by Flaburgan** [ubports/messaging-app#179]
It would be nice to display in the info the datetime the SMS has been sent, not only the one it has been received.

Steps to reproduce:
- Turn on flight mode
- With another phone, send a SMS to your phone
- Wait a few minutes
- Turn off flight mode and receive the SMS
- Go to the conversation and display the SMS info
- You will have "received" and "read" times there, but not sent one.

Maybe that's something for @lduboeuf :D

**Comment by lduboeuf** [comment]
confirmed, i will have a look, but i'm afraid it is at lower level
It occurs on notification too 
for reference, the object received from telepathy is here: https://telepathy.freedesktop.org/doc/telepathy-qt/a08524.html#a7e6cd37c4e31fadc780b9c1f49894b33
currently "received" is used. We should switch to "sent" date.
history-service and telephony-service is concerned. I will give a try if i'm able to build them :)

**Comment by lduboeuf** [comment]
Ok got it working! , so if anyone don't mind to have the sent datetime displayed instead of the received one, i will propose a PR soon. 

Impact: telepathy-ofono, history-service, telephony-service and messaging app 

Note that for messaging-app if we want to use both ( received date and sent date ), we need to change the model in history-service ( database, model, etc...) :  much work...

**Comment by Flaburgan** [comment]
Why not both? It implies to resize the popup?

**Comment by lduboeuf** [comment]
Would be better, but implies more work, database upgrade and some data migration has well as modifying the model, etc... So not a quick and short PR... :)

**Comment by Flohack74** [comment]
I think sent date is the right one to go for anyways. Because if you read a message 10hrs later I would like to know that ^^

**Comment by lduboeuf** [comment]
ok, so just replacing the received date by  the sent one is a quick thing to do, i will PR something soon.

**Comment by lduboeuf** [comment]
so finally, i've reverted the PR because some Pinephone users reported NULL sent date, see https://gitlab.com/ubports/community-ports/pinephone/-/issues/165

Some investigation need to be done before

**Comment by Flohack74** [comment]
Can this be closed now @lduboeuf ?

**Comment by lduboeuf** [comment]
not yet, the sent date on messaging-app still need to be done, and more over in history-service before. So finally i give a try to not replace  timestamp by the sent date but just to add a new column and model to history-service but the change is quite big...: https://github.com/ubports/history-service/pull/32/files

And i need to well test it before mark as ready for review.
So for now only sent date is used for message notification

**Comment by lduboeuf** [comment]
@Flohack74 
So i think i will not implement for OTA-14 the history-service/messaging-app part
For instance it generates too much changes/additions on history-service side and i'm afraid of any regressions. I need more time.
Please move it to OTA-15.

**Comment by Flohack74** [comment]
Oki sure.
