### ISSUE TITLE
SMS received more than once

### ISSUE THREAD

**Issue by lascapi** [ubports/messaging-app#18]
Hello, 
Sometimes I received a SMS more than once, with a few minutes between each sms. I don't know why. Usually I have the 2G activate.

I have a LG Nexus5 with Ubuntu15.04(r17)

**Comment by abkro** [comment]
I can confirm this behavior on my Nexus 5, channel RC, version 2019-W22.

It happens at irregular intervals. Last time it happened to me was yesterday. I received 2 copies of the same message at the same time.

**Comment by lduboeuf** [comment]
@abkro still occuring ?

**Comment by Flaburgan** [comment]
I had it today, I had two notifications about the same message, but after killing the app it is now displayed only once.

**Comment by abkro** [comment]
@lduboeuf - I unfortunately haven't had the time to stick a SIM in my N5 for a while. In connection with work I am dependent upon another device running Android. If I get the opportunity to test (maybe during Easter) I will report back.

**Comment by lduboeuf** [comment]
ok, i close it for now, feel free to create a new one or reopen it

**Comment by Flaburgan** [comment]
No occurrence for a while indeed.
