### ISSUE TITLE
Some longer texts extend outside of the text bubble (again)

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/messaging-app#183]
This bug seems to be back on BQ E5 HD. Seen on dev 488 tonight.
![SMS out of box](https://user-images.githubusercontent.com/50362604/77802260-c6b08680-707a-11ea-816a-03d15579048f.png)

For information, please note that the actual text of the SMS was long. At least fifteen lines

**Comment by gbdomubpkm** [comment]
Just a different case obtained yesterday to confirm
![Erreur longueur SMS](https://user-images.githubusercontent.com/50362604/78443012-cc106100-7678-11ea-88fc-1874b3a0956b.png)

**Comment by lduboeuf** [comment]
do you have any logs ? see something  /home/phablet/.cache/upstart/application-legacy-messaging-app-.log . Beware it can have sensitive data ( phone number )

**Comment by gbdomubpkm** [comment]
The mms about the error is from yesterday.  I kept it.
Is the log from now on if I open messaging-app useful?
Don't you need a copy (without sensitive data) of the log obtained JUST AFTER receiving a wrongly displayed SMS or MMS?

**Comment by lduboeuf** [comment]
you can show us logs when you display the conversation

**Comment by gbdomubpkm** [comment]
[application-legacy-messaging-app-.log](https://github.com/ubports/messaging-app/files/4432221/application-legacy-messaging-app-.log)
Yesterday conversation

**Comment by lduboeuf** [comment]
ok, don't see anything wrong, but if you say that it occurs with very long text, it should be testable

**Comment by gbdomubpkm** [comment]
I've identified part of the problem.  What is certain is that the error is systematic when receiving images accompanied by a text: see here the mms sent back to myself, and I have continuously found the error in old mms that I have saved.
![Erreur affichage SMS](https://user-images.githubusercontent.com/50362604/78461399-ce9aa700-76c8-11ea-8b21-452ac034724a.png)

**Comment by lduboeuf** [comment]
Can you please test that click and tell me if any progress ( rename the .zip extension in .click )


[messaging-app.ubports_0.0.0+testing-click-build_armhf.zip](https://github.com/ubports/messaging-app/files/4438675/messaging-app.ubports_0.0.0%2Btesting-click-build_armhf.zip)

**Comment by lduboeuf** [comment]
can you test this click ?

https://github.com/lduboeuf/lduboeuf.github.io/raw/master/messaging-app.ubports_0.0.0%2Btesting-click-build_armhf.click

**Comment by gbdomubpkm** [comment]
You can see, it seems to be good 👍
![AFFICHAGE MMS RÉSOLU06042020](https://user-images.githubusercontent.com/50362604/78568317-39132a80-7822-11ea-88d7-14a93699985a.png)

**Comment by lduboeuf** [comment]
and for your long conversation message, does it display well ?

**Comment by gbdomubpkm** [comment]
Actually, I was just checking.  I can confirm that the long text message from 19:48 is displayed correctly.  Everything looks good. 
 
Very efficient work 👍👍

To be totally sure, I'm going to go through all the bad postings I've kept and i'll send you a last confirmation.

**Comment by gbdomubpkm** [comment]
I checked my 'collection'.
EVERYTHING IS OK
Resolved.
Thank you
The fix should be pushed into  dev quickly ?

**Comment by lduboeuf** [comment]
i guess, as soon as OTA-12 landed, but you can still use the provided click if anything wrong with current app

**Comment by gbdomubpkm** [comment]
OK

**Comment by Keneda-ut** [comment]
Same issue here, with RC on MX4.

Will the app updated on OTA-12 or pushed on open-store?

**Comment by gbdomubpkm** [comment]
@Keneda-ut Even if the fix is not built into the OTA-12, you have the means to install and test any .click that is not present in the open-store.
To do this, you can do the following:
-download the .click of this bug report or another one;
-press the downloaded file;
-select 'open with';
-select 'Openstore' and the .click will be installed.
You will be able to use the two 'Messaging' applications in parallel and see the differences.
You can also uninstall any .click as usual (UTTT or Openstore).

**Comment by Thieb67k** [comment]
Dear all,
I have seen that problem recently for the very first time and the .click link solved the problem. Thanks!
I thought that link will solve the issue ubport/ubuntu touch/#1022 (Some received SMS are truncated (from the begining). Very last words are visible.)... But it did not.
Here an example (first white box; several upstream words are missing).
Best,
![screenshot20200701_143453031](https://user-images.githubusercontent.com/44848877/86244461-48e3a600-bba8-11ea-8162-0596a48e6a70.png)

**Comment by lduboeuf** [comment]
humm, the best as far as the message is not confidential is to provide the source of the message that can be obtained from the database /home/phablet/.local/share/history-service/history.sqlite if you are on Telegram you can post me in private ( same handle than github). Or just notice if the message in db is the same as shown here

**Comment by Thieb67k** [comment]
Well, I discover that tool...
The message is DB is the same: incomplete...
I just noticed that time into "eventId" and "timestamp" columns are differents: "2020-06-30T14:43:09+0200-10" Vs "2020-06-30T12:43:36.000Z" respectively. Is that normal? (I have the same thing with complete messages so I guess it is normal)

Side issue: Is that normal to see "broadcast:5169fb42d1f62a01383[...]" instead of phone number into "threadId" column?
Thanks.

**Comment by lduboeuf** [comment]
>The message is DB is the same: incomplete...

ok, so something wrong elsewhere, it could be at low level

> I just noticed that time into "eventId" and "timestamp" columns are differents: "2020-06-30T14:43:09+0200-10" Vs "2020-06-30T12:43:36.000Z" respectively. Is that normal? (I have the same thing with complete messages so I guess it is normal)

yes it is

> Side issue: Is that normal to see "broadcast:5169fb42d1f62a01383[...]" instead of phone number into "threadId" column?

That one just got fixed today ( but not landed), unfortunately this won't update the existing threadId see here https://github.com/ubports/messaging-app/pull/209

**Comment by lduboeuf** [comment]
@Thieb67k for your truncated message, can you have the original one from the sender, just to see if any weird characters, or trying to reproduce by sending it again. I suppose it does not happen every-times...

**Comment by Thieb67k** [comment]
That does not happen every times even though I feel it is getting worse (most frequent, begining and end of messages are truncated). The text contains some usual french characters that are not problematic for others messages.
Sending the exact same message does not help.
I even noticed that one or two messages are missing, yet the sender's messages notifications show that is allright...
I will send you some example on Telegram.

**Comment by lduboeuf** [comment]
humm sad. but out of this issue, follow up may be here https://github.com/ubports/ubuntu-touch/issues/1022
