### ISSUE TITLE
Vocal message records but doesn't send

### ISSUE THREAD

**Issue by Emphrath** [ubports/messaging-app#189]
If you use the microphone icon next to the text field to record a vocal message, it does record (in /home/phablet/.local/com.messaging) but nothing else happens.

Steps to reproduce : 
- long press the icon, talk , release.
Expected behavior: a mms is sent. 
actual behavior: nothing happens

**Comment by gbdomubpkm** [comment]
@lduboeuf  To complete, can you make sure that MESSAGING can also take into account text files (.txt, .pdf ) as attachments? That would also be very useful.
According to @cibersheep  clear explanation [here](https://gitlab.com/ubports/apps/filemanager-app/-/issues/83) once you have implemented the audio file manipulation and text manipulation, it will allow in reverse from FILE MANAGER to **open** these files **with** MESSAGING. Thank you

**Comment by Emphrath** [comment]
Messaging doesn't take these into account. neither text nor pdf. I can attach them using the "picture" attachment pop up, but in text case, it just sends the contents of the file as raw text (and actually doesnt send anything) and pdf doesn't even register. Then I tried the "reverse" way. messaging doesn't show up as an app I can "open with".

**Comment by Emphrath** [comment]
I'm on stable, and have document viewer and tedit installed

**Comment by gbdomubpkm** [comment]
> Messaging doesn't take these into account. neither text nor pdf. I can attach them using the "picture" attachment pop up, but in text case, it just sends the contents of the file as raw text (and actually doesnt send anything) and pdf doesn't even register. Then I tried the "reverse" way. messaging doesn't show up as an app I can "open with".

There is a misunderstanding. The request is for @lduboeuf ,not for you 😉

**Comment by lduboeuf** [comment]
humm who says i'm the maintainer :).
Though i will give a try for the audio thing

**Comment by lduboeuf** [comment]
And attachements seems to work AFAIK ( pictures, pdf, any format ) and it is true that text file are imported in the content of a message. Probably if any issue here is because of MMS issue ( and of course you need cellular data enabled  ). But lets concentrate on audio feature

**Comment by gbdomubpkm** [comment]
> humm who says i'm the maintainer :).
> Though i will give a try for the audio thing

corrected, sorry

**Comment by lduboeuf** [comment]
so fix is done,  you can test with the click package: https://github.com/lduboeuf/lduboeuf.github.io/raw/master/messaging-app.ubports_0.0.0%2Btesting-click-build_armhf.click
Note that to get audio playback working, you need to install the deb package available in the artifactory due to permission restriction.
But recording and sending should be fine

**Comment by Emphrath** [comment]
Sadly, it doesn't on my FP2. By the way, I can't send pdf or "any format" yet, so maybe the issue's on my side. What happens: the click package creates a new messaging icon. Now, when i press the record Icon, it brings up a permission popup, stating I should allow the messagingapp to access the microphone. I then go to permissions, where everything but location settings is grayed out and I can't do anything about it. Is it related to the deb package you mentioned ?

**Comment by Emphrath** [comment]
Update: for some reason, the permissions area "ungrayed" and your app was listed with access to the microphone. I then retried the operation and this time I could check "allow microphone access" when it popped up. And then it worked. Great job !

**Comment by Emphrath** [comment]
Will this be in OTA-12 ? Along with that deb fix ? Thanks again.

**Comment by lduboeuf** [comment]
i don't think so, it will probably with OTA-13. But if you want to keep that feature, just keep this click package installed :)

**Comment by lduboeuf** [comment]
humm better to keep it open since it is not merged ;-)

**Comment by gbdomubpkm** [comment]
@lduboeuf  
Hello.
I just did some checking.
There are some display problems with the test .click (Messaging) that do not occur with the original application (MESSAGE).
Tests done by sending to myself one or to audio messages. After audio, text messages...

BAD DISPLAY WITH MESSAGING .CLICK
![BAD DISPLAY 20200422](https://user-images.githubusercontent.com/50362604/80030541-a1cbf980-84e8-11ea-9423-e242390db689.png)

BAD DISPLAY 2 AUDIO WITH MESSAGING .CLICK (with received audio message hidden under the writing area)
![BAD DISP 2 AUDIO 20200422](https://user-images.githubusercontent.com/50362604/80030578-b0b2ac00-84e8-11ea-94fc-719800c269e4.png)

BAD DISPLAY AGAIN (with received audio message hidden under the writing area)
![BAD ZONE ECR 20200422](https://user-images.githubusercontent.com/50362604/80030621-bdcf9b00-84e8-11ea-870a-d67a2faa2185.png)

GOOD DISPLAY WITH APP MESSAGE :
![MESSAGE GOOD DISPLAY20200422](https://user-images.githubusercontent.com/50362604/80030647-c922c680-84e8-11ea-8a72-05ba0b7669f1.png)

**Comment by lduboeuf** [comment]
i see ;-), will see what i can do

**Comment by lduboeuf** [comment]
can you please install a new version and see what you get: https://github.com/lduboeuf/lduboeuf.github.io/raw/master/messaging-app.ubports_0.0.0%2Btesting-click-build_armhf.click

MMS is really messy on my device, i can't receive audio, i think i need a full reinstall...

**Comment by lduboeuf** [comment]
anyway backend also need some work as files seems not deleted even on cache folder and after reboot. It could grow pretty fast

**Comment by gbdomubpkm** [comment]
Nothing change, always bad display, the same.
I just realized there's no send and receive time on the audio messages.

**Comment by gbdomubpkm** [comment]
Maybe add a function in the Message app  settings to ( manually) clean the cache?

**Comment by lduboeuf** [comment]
humm ok, need to dig into it. For duration display it needs more work, will see later for that part

**Comment by lduboeuf** [comment]
can you please re-open that issue ?

**Comment by lduboeuf** [comment]
that one should fix the display issue: https://github.com/lduboeuf/lduboeuf.github.io/raw/master/messaging-app.ubports_0.0.0%2Btesting-click-build_armhf.click

**Comment by gbdomubpkm** [comment]
I confirm.  I've done a lot of different tests.  DISPLAY FIXED 👍

**Comment by lduboeuf** [comment]
for the duration displayed, i'm afraid it will not be possible atm because of heavy operations needed under the hood
Please reopen that issue since it is not merged yet

**Comment by gbdomubpkm** [comment]
@Emphrath  Please, can you reopen the issue. As it you who open the bug report, i don't think i can. Thank you.
