### ISSUE TITLE
Can't send a video

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/messaging-app#192]
Hello again !
I confirm https://forums.ubports.com/topic/4141/can-t-seem-to-send-videos-via-messaging-app
Tested with BQ E5 HD dev.
I can link a video to the message but i can't send it (icon not responsive). 
A video + a photo can't be sent too (icon not responsive).
If i delete the video and i keep the photo, i can send (icon responsive).

**Comment by BudRz** [comment]
I can confirm this as well.

**Comment by lduboeuf** [comment]
i can quick fix it, but i'm struggling with the icon displayed ( currently a video icon with a red circle as it was not available ) I will do a workaroud

**Comment by lduboeuf** [comment]
let's test with that one: https://drive.google.com/open?id=1HRbyIjrOSOQXeZ00euIvV8twB4eOTXGq

I can't test it here since MMS is not working well.~~@gbdomubpkm , note that this click does not include audio fix ;-)~~ 
[EDIT]: this click include several fixes as well as audio recording fix and video sending (hopefully)

**Comment by gbdomubpkm** [comment]
That is OK 👍
But the success of the sending also depends on the size of the video and the maximum size allowed by the data provider.
It might be a good idea for the camera to allow <480p resolution for the video mms,i think.
The com.ubuntu.messaging app cache keeps everything....
I can't see if it works in the FILE MANAGER --> MESSAGING direction because the video is sent back to the original Messaging application and not the .click.

**Comment by lduboeuf** [comment]
yes nothing is done for video compression AFAIK and cache management, but that another story
