### ISSUE TITLE
Retain the formatting of a written SMS message

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/messaging-app#194]
Question: when we write a sms and we do one or more line feeds ourself, when we send the sms, the formatting is not respected: the whole text is put afterwards.  Would it be possible to ensure that the basic formatting is respected? 

For example, we type :

xxxxxxxxxx:
    -xxxxx
    -xxxxxx
    - xxxxx

What is sent and received is:

xxxxxxxxxx : -xxxxx -xxxxxxx
-xxxxx

The goal would be to keep what We type.

**Comment by lduboeuf** [comment]
i've tested and the format is kept for the receiver ( non UT ), so it is more an issue in message-app in UT i guess

**Comment by gbdomubpkm** [comment]
So, you said that the formats are as i said using a UT phone when typing and sending a SMS and the reception on a non UT phone has the typed format ?

Do you know ? : would an update of qt in UT affect formatting in messaging-app ?  Or  it will only affect morph-browser and will have no effect in formatting (in messaging) ?

**Comment by lduboeuf** [comment]
i don't know if it comes from Qt version. I did some tests,  i had successfully displayed the formatted msg but the text is displayed as html, not the same font as usual...
I will try tomorrow

**Comment by lduboeuf** [comment]
![screenshot20200429_235601880](https://user-images.githubusercontent.com/11663835/80652347-0272ad80-8a78-11ea-98d1-a5cea92b78da.png)

**Comment by lduboeuf** [comment]
![1588198825165](https://user-images.githubusercontent.com/11663835/80652557-7319ca00-8a78-11ea-8af3-a80849d7ee7c.jpg)

**Comment by lduboeuf** [comment]
test click here: https://drive.google.com/file/d/1HRbyIjrOSOQXeZ00euIvV8twB4eOTXGq

**Comment by lduboeuf** [comment]
ok, done, test click here: https://drive.google.com/file/d/1HRbyIjrOSOQXeZ00euIvV8twB4eOTXGq:
![msg-app-done](https://user-images.githubusercontent.com/11663835/80683577-bc900680-8ac4-11ea-858e-77fff69df9d9.png)

**Comment by gbdomubpkm** [comment]
I'm working. I will test later this afternoon but thank you. First try it seems to be better.

**Comment by gbdomubpkm** [comment]
Thus after tests, the message appears really better formatted  but spaces at the beginning of lines in an enumeration are ignored. 

bbbb -test
bbbb -test
bbbb -test  corresponds in sending and receiving to :
-test
-test
-test

That's it, I think. 👍

**Comment by lduboeuf** [comment]
ok done, i updated click file

**Comment by gbdomubpkm** [comment]
The just previous version was finally better because this version created problems of cut in the middle of words on the SMS of prévious .click, and on the last sms of this .click the formatting is not great : see the 2 screenshots :

![screenshot20200430_141725914](https://user-images.githubusercontent.com/50362604/80711293-6c2e9e00-8af0-11ea-809f-e4477022b3b3.png)


![screenshot20200430_141901135](https://user-images.githubusercontent.com/50362604/80711362-8799a900-8af0-11ea-8f23-29060fd88e43.png)

**Comment by lduboeuf** [comment]
humm there is something with the "-" char. But not for all cases, Lets keep it for now, if we see more side effects.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/194

Sorry for your inconvenience.
