### ISSUE TITLE
Visual improvement for grouped sms in messaging App?

### ISSUE THREAD

**Issue by Thieb67k** [ubports/messaging-app#199]
### Description of the feature
In the message app, grouped messages are greyed out and when you want to delete them, the trash can is also greyed out: Feeling of function inactive.
Why does this happen to grouped messages? Is there another visual available? 

- Device: mako LG Nexus4
- Channel:Stable

**Comment by UniversalSuperBox** [comment]
Hi @Thieb67k,

I've transferred this issue to the messaging-app repository. Could you add some screenshots of the problem, and of a message which does not exhibit this behavior?

**Comment by lduboeuf** [comment]
it is true that broadcast thread displays like inactive controls. IMO we should remove that specificity as broadcast thread is already identifiable with the icon

**Comment by lduboeuf** [comment]
@cibersheep what do you think ?

**Comment by cibersheep** [comment]
Could you provide a screenshot?

**Comment by Thieb67k** [comment]
Hello,
here some screenshots of the greyed out fields, but still active. It is just a feeling that the fields are 
not clickable/active.
Best,

![Capture d’écran du 2020-05-13 09-10-52](https://user-images.githubusercontent.com/44848877/81782919-d7b63980-94fa-11ea-839d-c0039fb9e7d3.png)
![Capture d’écran du 2020-05-13 09-11-54](https://user-images.githubusercontent.com/44848877/81782933-ddac1a80-94fa-11ea-990f-30b1cd001e37.png)
![Capture d’écran du 2020-05-13 09-12-20](https://user-images.githubusercontent.com/44848877/81782939-e1d83800-94fa-11ea-9d14-8ff35ec282f1.png)

**Comment by cibersheep** [comment]
I see. That's definitively a bug and looks like disabled indeed. Thank you for reporting.
@lduboeuf you are right, the icon should be enough, no other styled needed

**Comment by lduboeuf** [comment]
@cibersheep you do, i do ?

**Comment by cibersheep** [comment]
Go for it! If you need help shout(, should let it all ooooout)
