### ISSUE TITLE
SMS Detail is not shown only after reboot

### ISSUE THREAD

**Issue by delijati** [ubports/messaging-app#202]
When i receive a SMS i can see the SMS in the ListView. But when i click the SMS detail all history and the message are not loaded. 

OTA-12  Bq Aquaris E4.5 (krillin)

**Comment by lduboeuf** [comment]
humm do you have any logs ?
Is it always the case or randomly or for a specific conversation ?

**Comment by lduboeuf** [comment]
@delijati i close it for now since no news. Issue can be reopened if it occurs again
