### ISSUE TITLE
Group Texts are not Working

### ISSUE THREAD

**Issue by edwardwilhelm** [ubports/messaging-app#204]
**Main Problem**
When I send a group text, each recipient receives the text for me individually, not me in the group. 
When when I am a recipient in a group text sent from someone else, I receive nothing at all. To the best of my knowledge, this happens for my group text interactions for both Android and Iphone, however I have access to iPhones to test the issue. I can confirm that the texts are green on the iPhones.

**Sub-Problem 1**
I also occasionally receive weird texts from "x-ofono-unknown". I think this is a related issue.
Picture of what exactly is sent here: https://forums.ubports.com/assets/uploads/files/1590451968152-ofono.png

**Sub-Problem 2**
I also have trouble with formatting of certain texts into the box. Sometimes there is no line break.
Picture of the Problem here: https://forums.ubports.com/assets/uploads/files/1590451987631-line-break.png

I have a hunch that this all somehow relates to MMS, and that sub-problem 1 and 2 may be related to the main problem. I am however able to send and receive pictures, as long as they are not in a group of course. 

Oneplus One - UBorts image part 20200428-12824 - Release Candidate

**Comment by lduboeuf** [comment]
yes, mms group texting is a known issue, we are all waiting for a volonteer to work on it. There is a start here https://github.com/ubports/telepathy-ofono/pull/6
For the sub problem 2, it is already reported here : https://github.com/ubports/messaging-app/issues/194 . And a PR is waiting to be merged.

**Comment by edwardwilhelm** [comment]
Okay, thanks.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/204

Sorry for your inconvenience.
