### ISSUE TITLE
Phone numbers are being included in error logs

### ISSUE THREAD

**Issue by stuarttempleton** [ubports/messaging-app#206]
Phone numbers are included in some error logging information (application legacy messaging app?), making them unsuitable for safely sharing logs with developers via public bug tracking without modification.

FYI, This is similar to the logging being done by the dialer app, so it's possible it's part of a subsystem I'm not aware of and might be considered duplicate.

**Comment by lduboeuf** [comment]
added an issue on the component responsible for adding logs here: https://github.com/ubports/telepathy-ofono/issues/12

**Comment by Flohack74** [comment]
Closing in favor of the mentioned report in telepathy-ofono
