### ISSUE TITLE
Devel: message not stored and displayed

### ISSUE THREAD

**Issue by lduboeuf** [ubports/messaging-app#220]
This PR could be a OTA-13 blocker : 
need to have confirmation because my database can be very messy since with all my tests.
I faced several issues:
- Outgoing message: The message is effectively sent but still appears as pending.
- Incoming Message: Notification of new message is ok but does not appear in the conversation view nor storee in the database ( it happens for several contacts but not all)
- Writing a draft and go back to thread list triggered a Lomiri reboot

If confirmed, we need to revert that PR

https://github.com/ubports/messaging-app/pull/167

**Comment by lduboeuf** [comment]
I've cleaned my db, and no issues found so far since 3 days

**Comment by Flohack74** [comment]
so can we close it?

**Comment by lduboeuf** [comment]
After a database cleanup, i don't have any issues. Need to be confirmed by others.

**Comment by lduboeuf** [comment]
So did have any issue since. I suspect it was my database
