### ISSUE TITLE
Dev (only ?) No red trash icon : can't delete audio and picture mms

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/messaging-app#221]
I just noticed this on BQ E5 HD dev 567 (but it may be the case on the other channels): for a phone number, in the history of a SMS,  it is impossible for me to make the red trash icon appear by sliding the finger to delete an audio mms,   and picture mms IF there is no text with. 
Moreover, i noticed it's impossible to add a text in an audio mms.

**Comment by lduboeuf** [comment]
Yes confirmed for the selection issue on audio file.
and not possible to add a message with a voice message too but i think it is intentional for that one. A voice message  is meant to replace a text message

Please split the report when there is several issues
