### ISSUE TITLE
MMS : cannot attach an audio file recorded in a folder

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/messaging-app#222]
I can't attach an audio file (e.g. ogg format) and send it as mms.
For example I would have liked to be able to select a voice memo recorded with the recorder app (dictaphone) and send it as mms.

**Comment by lduboeuf** [comment]
humm can't reproduce on N5 ( devel ). Have you tried from the File Manager to the messaging app, or messaging-app-> attachments-> select from File Manager ?

The "picture" icon is not relevant in that case

**Comment by gbdomubpkm** [comment]
On OPO, NEXUS 5, BQ E5 HD the only options to attach recorded files are for IMAGE, VIDEO, CONTACT. Yes, if i want to attach an audio file, i get a big 'useless' empty paper clip.. Do you get a workable audio attachment ?

**Comment by lduboeuf** [comment]
yes, by clicking on the IMAGE icon-> File Manager.
My test is on a 550kB file only

**Comment by gbdomubpkm** [comment]
I Don't understand why it doesn't work for me. Can you see me a screenshot of the audio attachment ?

**Comment by lduboeuf** [comment]
![screenshot20200812_223744389](https://user-images.githubusercontent.com/11663835/90065471-9f3a1d80-dcec-11ea-9fd1-8feb9d881129.png)

**Comment by gbdomubpkm** [comment]
..... Yes i agree,  this also work for me when i record directly in messaging app an audio file.  But what i wanted to do is to attach a little audio  memo  which is in a folder that i have recorded before with recorder app or a little music  mp3...

**Comment by lduboeuf** [comment]
the example above come from a ogg file that i took from the FileManager

**Comment by lduboeuf** [comment]
a test to be done is to have a clean database and see if it can come from it.
Or the file size may be too big.
Or is OPO having issues with Content-Hub ?

**Comment by gbdomubpkm** [comment]
I don't understand !! It doesn't work with 3 different smartphones !! And with little audio files. Must be check with somebody else than you and me.

**Comment by lduboeuf** [comment]
what the logs says ?

**Comment by gbdomubpkm** [comment]
I send to me an 'ogg empty paper clip'
I deleted my phone. Now 0000000000

Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
Creating a QMirClientScreen now
Starting application from src/main.cpp
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.137\" (uid=32011 pid=12111 comm=\"messaging-app \") interface=\"com.canonical.libertine.Service.Operations\" member=\"list\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=3000 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.137\" (uid=32011 pid=12111 comm=\"messaging-app \") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"running\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=3000 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.137\" (uid=32011 pid=12111 comm=\"messaging-app \") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"last_error\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=3000 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.137\" (uid=32011 pid=12111 comm=\"messaging-app \") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"result\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=3000 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
file:///usr/share/messaging-app//MainPage.qml:253: TypeError: Cannot read property 'status' of null
QQmlExpression: Expression file:///usr/share/messaging-app//FavoriteChannels.qml:89:25 depends on non-NOTIFYable properties:
    QQmlSettings_QML_24::category
QQmlExpression: Expression file:///usr/share/messaging-app//FavoriteChannels.qml:89:25 depends on non-NOTIFYable properties:
    QQmlSettings_QML_24::category
file:///usr/share/messaging-app//Messages.qml:1626:5: QML ComposeBar: Binding loop detected for property "attachmentModel"
qml: 0
file:///usr/share/messaging-app//Messages.qml:1626:5: QML ComposeBar: Binding loop detected for property "attachmentModel"
qml: 0
[PERFORMANCE]: Last frame took 42 ms to render.
file:///usr/share/messaging-app//ComposeBar.qml:640:5: QML AttachmentPanel: Binding loop detected for property "height"
qml: 0
"ofono/ofono/account0" "2020-08-13T00:36:00Z-1" "/org/freedesktop/Telepathy/Connection/ofono/ofono/connection_6872ee9f7d36b362606155292f7b764b/TextChannel0" QMap(("chatType", QVariant(int, 1))("participantIds", QVariant(QStringList, ("0000000000")))("threadId", QVariant(QString, "broadcast:df85198d1825bee929a363fbd98e73d7")))
adding channel "/org/freedesktop/Telepathy/Connection/ofono/ofono/connection_6872ee9f7d36b362606155292f7b764b/TextChannel0"

**Comment by lduboeuf** [comment]
humm it doesn't say much. Maybe just try with an empty database ?

**Comment by gbdomubpkm** [comment]
Hi @cibersheep 
As i think you have a BQ E5 HD, can you test if it works for you ? Thank you in advance.

**Comment by lduboeuf** [comment]
@gbdomubpkm still having issue ?

**Comment by gbdomubpkm** [comment]
Yes.
It doesn't work (for me only?).
Someone else will have to test.

**Comment by lduboeuf** [comment]
> On OPO, NEXUS 5, BQ E5 HD the only options to attach recorded files are for IMAGE, VIDEO, CONTACT. Yes, if i want to attach an audio file, i get a big 'useless' empty paper clip.. Do you get a workable audio attachment ?

So i've tried it again, pictures->File Manager -> select the ogg file. Then i have that:
![screenshot20201007_092403716](https://user-images.githubusercontent.com/11663835/95300092-fa1c6b00-087e-11eb-9617-18088b957eb2.png)

If i send it, it is displayed as an audio file like there: https://github.com/ubports/messaging-app/issues/222#issuecomment-673098955

My ogg test file: https://drive.google.com/file/d/1L3PPHAmpD1qihgpSDmXL7USkcw2B3ZOV/view?usp=sharing

**Comment by gbdomubpkm** [comment]
Exact. It works with your file ! You are right !!

I tried with ogg file recorded with Recorder app (Luksus) and the ogg file is shown as a video, not an audio file ! Can you test that ?

**Comment by gbdomubpkm** [comment]
It also work with mp3 !!

It might be a good idea to have an  audio file selection icon when attaching an audio file  instead of using the image icon and to see an other thing that a paper clip as attached file..

**Comment by gbdomubpkm** [comment]
I tried with the flac format of recorder app, shown as an audio file,  and it works.

**Comment by lduboeuf** [comment]
So is it working now (except the Picture icon is not relevant ) ?

**Comment by gbdomubpkm** [comment]
It works yes  ( but not with ogg file of recorder app).

**Comment by lduboeuf** [comment]
ok, i can reproduce. The ogg file generated from dictaphone is recognized as `"application/x-matroska`, that could be the cause. 
You can check with https://htmlstrip.com/mime-file-type-checker, it recognized also as a application/x-matroska.
 So something wrong in dictaphone recording i would say

**Comment by lduboeuf** [comment]
Close at it is not related to messaging-app AFAIK
