### ISSUE TITLE
new message is overwritten by the draft when selecting a contact

### ISSUE THREAD

**Issue by lduboeuf** [ubports/messaging-app#235]
1st case: Forward a message, choose a contact who have a draft, forwarded message text will be overwritten by the draft.
2nd case: Write a new message, then choose a contact, if any draft, the current message will be overwritten by the draft.

**Comment by UniversalSuperBox** [comment]
Case 2 was tested in https://github.com/ubports/messaging-app/pull/234#issuecomment-717098300

Case 1 is still untested.
