### ISSUE TITLE
last messages are not shown when called from url-dispatcher

### ISSUE THREAD

**Issue by lduboeuf** [ubports/messaging-app#240]
Step to reproduce:
From contact app, select a contact and click on sms icon, the conversation is shown, all messages retrieved ( if any ) but we need to scroll down to see the last message

**Comment by jezek** [comment]
Device: FP2
OS: 2020-W43

- From ```contacts-app``` selected an contact and clicked he SMS button:
  The ```messaging-app``` was opened (or focused if already opened) and after a second the view changes to contact conversations showing last message and opens keyboard.
  Note: Some times the keyboard didn't pop up. I found out, that it happens on contacts, which weren't opened in ```messaging-app``` before (after the first fail, the keyboard shows every time).

**Comment by UniversalSuperBox** [comment]
@lduboeuf do you think the keyboard not appearing on the first selection of a contact is worth reporting separately?

**Comment by lduboeuf** [comment]
yes better, and not a regression as it always been there ( less often now since recent fix)

**Comment by jezek** [comment]
@lduboeuf @UniversalSuperBox I've created new issue #251
