### ISSUE TITLE
Impossibility of deleting a picture from a conversation.

### ISSUE THREAD

**Issue by Thieb67k** [ubports/messaging-app#245]
Dear all,
I have experienced the impossibility of deleting a picture, which failed to be sent, from a conversation thread.
Best,

**Comment by lduboeuf** [comment]
humm, are you on devel ? 
https://github.com/ubports/messaging-app/issues/238 has been fixed

**Comment by Thieb67k** [comment]
I am on stable, always :)

**Comment by lduboeuf** [comment]
so i can close it :)

**Comment by Thieb67k** [comment]
You are lucky.
I have tried again, but unfortunately, left/right swipe is not possible on the picture I am talking about. But with the texts below/above, I can! Cannot understand that.
My shopping list has to remain for eternity on that phone :)

**Comment by lduboeuf** [comment]
workaround: you can long press on a text message, and then select the pictures

**Comment by Thieb67k** [comment]
Yes! Well spotted.
