### ISSUE TITLE
Contact icon always red

### ISSUE THREAD

**Issue by Thieb67k** [ubports/messaging-app#246]
Dear all,
Opening a message via a notification shows me the contact icon (the initials) in a red square, instead of the real color. Yet, when I quit the message, I see the correct color into the messages list.
Best,

**Comment by lduboeuf** [comment]
Again please precise if you are on devel ?
I don't reproduce it

**Comment by lduboeuf** [comment]
Oh yes i see, confirmed, only when opening a message from the notification bar

**Comment by Thieb67k** [comment]
Alway on stable from my side.
Exactly! Only opening the notification.
Thanks

**Comment by Thieb67k** [comment]
I feel that the icon is red because the app did not identify the contact (when opening with notification bar). Because it is red with the man symbol, no initial. Yet, within the messages list, the icon has the proper color, with initial, no man symbol.
I hope that can help.

**Comment by Thieb67k** [comment]
Update:
That happened again once or twice (since OTA-17).
All contacts are red with the phone number instead of the name within the conversations list. But this time, after selection of one contact, the name, still in red, appears. Not the phone number.
Reboot helps.

**Comment by lduboeuf** [comment]
@Thieb67k  can you remember when it occurred ? Normal messaging app opening, after clicking on notification, other ?
Please if you can add some logs if any

**Comment by Thieb67k** [comment]
Last time occurred the 14th of June. Yes, I can reach the messaging app within the notification.
How could I do for log?

**Comment by lduboeuf** [comment]
@Thieb67k if not from `.cache/upstart/application-legacy-messaging-app.log` you can get the messaging-app logs with logviewer app.

**Comment by Thieb67k** [comment]
With file manager the is no "application-legacy-messaging-app". Which folder, from logviewer app, I have to select to find a messaging app logs? There is no "messaging" or something similar...

**Comment by Thieb67k** [comment]
Here sreenshot of what I can see with logviewer
![screenshot20210616_100442412](https://user-images.githubusercontent.com/44848877/122182434-937a3300-ce8a-11eb-88b4-3011e1b2277b.png)
![screenshot20210616_100449985](https://user-images.githubusercontent.com/44848877/122182440-94ab6000-ce8a-11eb-9f74-eb4c34deb049.png)

**Comment by lduboeuf** [comment]
@Thieb67k start at least one time messaging-app, it will appear after

**Comment by lduboeuf** [comment]
@Thieb67k  is this issue still here ?

**Comment by Thieb67k** [comment]
I haven't seen that for a while.

**Comment by lduboeuf** [comment]
ok, so i close it for now, thx
