### ISSUE TITLE
Character counter for SMS/MMS

### ISSUE THREAD

**Issue by Flohack74** [ubports/messaging-app#25]
_From @buchnerh on March 11, 2018 10:55_

-------- FEATURE-REQUEST -------------------------------------------------------

### Description of the feature

It might be useful if there will be a counter of already typed characters in a SMS. It would be nice if the structure can be like this:

67/160(1)

--> 67 characters already used from the available 160 characters. The 1 in brackets mean, that this is the first SMS. So if you type more than 160 characters the counter may look like this:

34/160(2)

or like this:

194/320(2)

I don't know if there's a similar limitation for MMS because I don' use this, but if it exist, this counter would be useful for MMS too.

- Device: BQ Aquaris E4.5
- Channel: 15.04 stable

_Copied from original issue: ubports/ubuntu-touch#519_

**Comment by ebeton-ro** [comment]
Please, be aware of SMS max limit of 3 messages (480 characters) before  converting the current message to MMS, at least this is the current behavior on Android and iOS.

**Comment by lduboeuf** [comment]
i see some sms counter related code in the repo but not visible, what is the status of that ?

**Comment by Flohack74** [comment]
Someone tried to work on this but maybe it was never finished. I do remember however to at least have it seen in action some day. If you like fix it ;)

**Comment by lduboeuf** [comment]
Oh just realize that there is a working sms counter that appear when reaching first 160 chars, so that issue can be closed i guess

**Comment by Flohack74** [comment]
Hmm when does it appear, at 160 or earlier :) because at 160 its not very useful probably xD

**Comment by lduboeuf** [comment]
seems to be 10 chars before reaching 160, but it display then "10/1" and then count down until reaching the "160/2", a little weird

**Comment by lduboeuf** [comment]
so sorry, maybe we can keep that open for further enhancement :)

**Comment by Flohack74** [comment]
Nah just file a new bug please. The feature is there, but now its broken ^^
