### ISSUE TITLE
Devel: Message bubbles not fully visible

### ISSUE THREAD

**Issue by lduboeuf** [ubports/messaging-app#263]
![screenshot20210119_233349231](https://user-images.githubusercontent.com/11663835/105102249-24e9a280-5aaf-11eb-91b3-f5af89fc7c1c.png)

**Comment by dobey** [comment]
I've managed to stuff some sent messages into the `history.sqlite` on my test device, but I don't see this issue. What is needed for the problem to occur? Also, the colors don't seem to match with what's in the screenshot here.

**Comment by lduboeuf** [comment]
confirmed even after a full OS reinstall on devel BQ4.5. So nothing special nedded to have the issue

**Comment by dobey** [comment]
Weird indeed. it does happen on sent messages only, and on my e4.5 but not my nexus 4.

**Comment by cibersheep** [comment]
Sent messages are visible (SuruDark and Ambiance on E5)

**Comment by dadandalive** [comment]
Same for Nexus 5 (as well both for SuruDark and Ambiance)
