### ISSUE TITLE
Message layout

### ISSUE THREAD

**Issue by TommyUB** [ubports/messaging-app#269]
I have two issues with the layout of the messages window.

1.  The text is small and it would be nice to be able to make the text a little larger to be easier on the eyes.
2.  When sending messages there is a green bubble encompassing the message if it goes through, and red if it doesn't.  This is fine but instead should be a lighter shade of red and green for bubbles, because if I send a person a link in a message it isn't going to show up to me as white text like other text in a message, it shows up to me as blue text in a dark green bubble which is very hard to read.  I know the person on the other end will not see it like this but it would be nice for the sender to be able to confirm they typed a link correctly by just looking at it, and it is almost impossible to see with the dark colors.
EDIT:  Another option to solve this 2nd problem would be to force all text to show as white, even if it is a link that was sent, which would just show as white underlined text.  I would be fine with that too, whichever works best.

**Comment by lduboeuf** [comment]
For the 1st, have you tried to scale up a bit with Tweak Tool ? , i think it should be a global configuration, not sms only.
For the 2nd, i agree that the link is not very visible, @cibersheep we should just displayed it as normal text ( theme.palette.normal.positiveText ) ?

**Comment by cibersheep** [comment]
> For the 2nd, i agree that the link is not very visible, @cibersheep we should just displayed it as normal text ( theme.palette.normal.positiveText ) ?

That could work

**Comment by dadandalive** [comment]
I confirm links in sent SMSes are shown in white now, and are well readable in both SuruDark and Ambiance mode (on Nexus 5, RC 2021-W10). I didn't try out messages that failed to send.
