### ISSUE TITLE
Compatibility of the history.sqlite file between old Androïd and Androïd 9

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/messaging-app#274]
For me, it is attempts between BQ E5 HD OTA-15 and Volla UT dev channel.
Only tested SMS, not call to somebody else.

I copied the BQ history.sqlite file on the Volla : no problem : so i have the BQ sms conversations on the Volla. 

According to my tests, i can't use my own conversation (my phone number) to send a sms to myself (and i think to somebody else)  : sending impossible, sms doesn't go.
Can you reproduce this ? If yes, does it mean that the history.sqlite file is (currently ?) incompatible between Androïd versions ? Can you make it compatible ?

I also made a test with contacts.db copied on the Volla and sending sms to myself : it works BUT all my phone number  BQ conversation is replaced by a blank, only stay sms send from the volla.

**Comment by lduboeuf** [comment]
hi, i doubt history.db is the culprint, to be sure you would need to have an empty history db and see if it is working.

**Comment by gbdomubpkm** [comment]
Hi. Ok thank you, but where should be history.db ? I don't see see that on the volla. And if it is somewhere, how to proceed ?

**Comment by lduboeuf** [comment]
i mean the history database as you mentioned above.Just remove it and restart your phone.
~.local/share/history-service/history.sqlite

**Comment by gbdomubpkm** [comment]
Yes there is no problem when there is no history.sqlite in the Volla or when the Volla creates his own history.sqlite but
is there a misunderstanding ? What i want IS to use the BQ history.sqlite in the Volla and it is that's what creates the problems discribed i would like to avoïd.

**Comment by lduboeuf** [comment]
Yes, i see, there is not a one-click way to do it. Some informations such as the account name might be different between devices, there is not an automated way to do it unfortunately

**Comment by gbdomubpkm** [comment]
Okay.  Too bad, it would have been useful for everybody to be able to continue to use this history.sqlite of an old based Androïd UT phone properly in a more recent based Androïd UT phone.
It was no problem for me to use a BQ 4.5 history.sqlite file in a BQ 5 HD, and maybe in a Nexus 5, not sure.
No problem currently tu use the contacts.db file transfered from the  BQ in the Volla though.

**Comment by lduboeuf** [comment]
If you are comfortable with SQL, this should be doable, the account id might be the thing to change.

**Comment by gbdomubpkm** [comment]
no, alas.
Maybe someone will.
Thank you for your analysis.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/274

Sorry for your inconvenience.
