### ISSUE TITLE
for non MMS users: make attachment and audio icons not visible

### ISSUE THREAD

**Issue by lduboeuf** [ubports/messaging-app#278]
This is more a question. Is it still accurate to     display features that users will never use and instead let the compose bar full width

**Comment by lduboeuf** [comment]
@cibersheep ? ^
Users that have mms disabled will not be able to send attachments, so maybe better to show icons with a disable sryle or not display them anymore ?

**Comment by lduboeuf** [comment]
@cibersheep do you have an opinion ?

**Comment by cibersheep** [comment]
Ooops... sorry this might got lost in the cracks.
Yep, I think this is a good idea if I understand it correctly. If those are options not available when MMS is disabled, then I think is good to hide them

**Comment by lduboeuf** [comment]
to test: Disable MMS in messaging-app settings, you should not see attachment, sticker or audio icon in the compose bar:

**Comment by nastyagrifon** [comment]
Device: Google Nexus 7 2013 LTE "deb"
Channel: Edge
Build: 2022-06-08

MMS is disabled
Attachment, sticker and audio buttons are still [visible](https://imgur.com/a/bieaAsk)

**Comment by Flohack74** [comment]
@lduboeuf can you check that? It might be that this is due to the App importer failing to import latest app. @NastyaGrifon can you please check if there are any system app updates, and install them if so? And then retest

**Comment by nastyagrifon** [comment]
> any system app updates, and install them if so? And then retest

Just installed the system today, no updates available

**Comment by lduboeuf** [comment]
> @lduboeuf can you check that? It might be that this is due to the App importer failing to import latest app. @NastyaGrifon can you please check if there are any system app updates, and install them if so? And then retest

Tested on my device on devel. It is ok.
I wonder if edge is still up to date ?

**Comment by Flohack74** [comment]
@NastyaGrifon on which channel are you? You can switch to devel maybe also

**Comment by nastyagrifon** [comment]
> You can switch to devel maybe also

Initially I've tested on edge. Changed the channel to devel, installed all the updates (2022-06-08). All the buttons are still there

**Comment by lduboeuf** [comment]
@NastyaGrifon , weird..., could you provide messaging-app logs ?

**Comment by lduboeuf** [comment]
@NastyaGrifon you confirm that you've disabled the MMS option in messaging-app settings ?

**Comment by nastyagrifon** [comment]
Yes, the MMS options is turned off. Just to be sure, I turned it on and then off again. Buttons are still there

[here](https://pastebin.com/E93Yzv4v) are the logs

**Comment by lduboeuf** [comment]
i don't see anything wrong in the logs. Maybe give another try with the last RC ( or devel )

**Comment by Flohack74** [comment]
Can I have a definite works/does not work on that one?

**Comment by rafree** [comment]
I just tested it: Switched off MMS in the settings, and I still see the icons when pulling up to compose a new message -> Does not seem to work.

Device: Miatoll
Channel: RC
Build: 2022-W24

**Comment by Flohack74** [comment]
Humm seems to work for me strange. @lduboeuf any ideas still what can be wrong?

**Comment by ivoxavier** [comment]
Tested on N5 and with MMS disable, icons for attachment and stickers still there.

RC Channel: 2022-W25

**Comment by lduboeuf** [comment]
humm, idk, can someone confim it does not work also after restarting messaging-app ?

**Comment by ivoxavier** [comment]
Tested that way and all the icons still visible

**Comment by lduboeuf** [comment]
Humm, i really don't, see, @Flohack74 i've made a small fix https://github.com/ubports/messaging-app/pull/342, i doubt it will correct the issue.
BTW we can reopen that ticket and let it like that since there is no regression

**Comment by gbdomubpkm** [comment]
![screenshot20220625_043707543](https://user-images.githubusercontent.com/50362604/175755218-85c2aeb3-199d-4722-8161-7004838d6030.png)

**Comment by gbdomubpkm** [comment]
... but I checked out of curiosity: not fixed on the BQ E5 HD (newer RC) and pinephone (newer DEV).

**Comment by Flohack74** [comment]
@lduboeuf we will tasckle this on OTA-24 if needed. I consider this not to be a release blocker.

**Comment by lduboeuf** [comment]
@ivoxavier Oh, one more question. Do you have a SIM card in the FP2 ?

**Comment by ivoxavier** [comment]
No, the FP2 has no SIM card. I can make the swap later when I'm home and get back to you with that use case

**Comment by ivoxavier** [comment]
@lduboeuf I did not get the SIM CARD in the FP2, but I had to switch to another phone, and the icons are now visible in 6T with the option MMS disable and without SIM CARD on 6T

**Comment by lduboeuf** [comment]
so if it does not work when no SIM card it is not a problem according to me

**Comment by matzgewinn** [comment]
Device is OnePlus5, RC channel, 2022-W45: Fix works. When mms attachments are disabled, the attachment-icons in the composing field are NOT visible.
