### ISSUE TITLE
Selecting messages in thread for mass operation

### ISSUE THREAD

**Issue by jezek** [ubports/messaging-app#28]
On my old phone BQ Aquaris E5, with original Ubuntu Touch from Canonical, I could select some messages in thread (by holding finger longer on message) and then mass delete them.

On my current phone FP2, with Ubuntu Touch from ubports (15.04 (r3) stable) this message selection does not work. It does work with threads, but not with messages in thread anymore.

~~Is it a bug, or a feature? Cause if selecting messages was deliberately removed, it was not a wise move.~~

**Comment by jezek** [comment]
I found out, that in thread view you can long-hold on whole line (icon, name, last message preview, time), to turn select mode on.

In thread messages view the you have to long-hold on left or right edge to turn select mode on. And it is not successful every time.

So selecting messages is working, but not as before, but in strange, non-intuitive way.

**Comment by Thieb67k** [comment]
I was looking for such a tip! Thank you.
I will try if I notice that unexpected behaviour.

**Comment by Thieb67k** [comment]
Actually, yes, the behavious is unexpected.
I did use the "select all" button then deselect manually 2 messages to keep them. Everything disappear...

**Comment by Thieb67k** [comment]
Other behaviour:
After selection and deletion, messages nevertheless remain...

**Comment by jezek** [comment]
After update to 2020-W33 (device: FP2), the mass selection in message thread and mass operations on selection (delete, use in message) are working as expected. Kudos to the fixer.

**Comment by lduboeuf** [comment]
Thanks, there still an issue with voice message though that don't trigger mass selection when long press on it but can't fix it now
