### ISSUE TITLE
Number of unread messages on Launcher icon

### ISSUE THREAD

**Issue by jezek** [ubports/messaging-app#280]
It would be nice, if the messaging-app would show number of unread messages in icon, like teleports does.

**Comment by lduboeuf** [comment]
good point, i see there is some code already handling that, need to see why it is not displayed

**Comment by lduboeuf** [comment]
humm, but it seems to works, i see in green bubble the number of unread messages, can't you confirm  @jezek ?

**Comment by jezek** [comment]
I don't mean this icon,
![screenshot20210310_161309651 resized 25% censored](https://user-images.githubusercontent.com/5408235/110653244-5e8c7f00-81bd-11eb-90df-46c8ee75bc35.jpg)
I mean this icon.
![screenshot20210310_161259627 resized 25%](https://user-images.githubusercontent.com/5408235/110653288-664c2380-81bd-11eb-9eb6-78460078ad16.jpg)

**Comment by lduboeuf** [comment]
oh i see :+1:

**Comment by lduboeuf** [comment]
So give some tries, it seems to work, but the emblem counter does not appear after boot as history-service is started before the session and it seems that we can't make it visible at that state. We have to launch messaging-app or receive a message to make it visible...
I'm looking for a way to subscribe to "session start" event to give a try, if anyone have and idea how to do that

![screenshot20220425_093128683](https://user-images.githubusercontent.com/11663835/165041453-51780c13-d65b-4332-a981-85a713ef55d9.png)

**Comment by jezek** [comment]
Du you have some draft for this ~~issue~~ feature?

**Comment by lduboeuf** [comment]
yes on my repo, just did a push: https://gitlab.com/lduboeuf/history-service/-/tree/xenial_-_emblem_counter
Sadly i've lost a part of my work, but that still ok for testing

**Comment by lduboeuf** [comment]
related MR: https://gitlab.com/ubports/core/history-service/-/merge_requests/17

testable via `sudo ubports-qa install PR_history-service_17`

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/280

Sorry for your inconvenience.
