### ISSUE TITLE
Message App broken as in Ubuntu Touch 101 from rc channel

### ISSUE THREAD

**Issue by truscellino** [ubports/messaging-app#288]
I have two devices, bacon and hammerhead, both on rc channel. Today both received a new image v101 and the messaging app is broken:
* history of sms texts has disappeared (but does not seem to be erased as it reappears when switching back to stable channel)
* I can't select contacts if I try and write a new text message, and the app freezes at that point, so no way to create messages

Already discussed in a forum post: [Message App broken with UT v101 on rc channel ](https://forums.ubports.com/topic/6179/message-app-broken-with-ut-v101-on-rc-channel)
Additional comment from AppleLee:

> I'm back to stable and my history is back too but no trace of the received messages while with RC 101

Thanks

**Comment by AppsLee** [comment]
Additionally I was able to select a contact, type a message and send it (as in tapping the arrow button).
But the SMS never reached destination and no trace was found in the history.
No running circle nor message thread created.

Nexus 5 on same RC channel.

**Comment by mihaelmilea** [comment]
Pro5 (turbo) here, rc101, messaging app opens but no messages. I didn't try to send any new messages.

Actually, in Settings, in the Recent Updates List, it is version 100 that I downloaded and istalled on May 19th...

**Comment by lduboeuf** [comment]
Thanks for the feedback, I'm working on it, will ping you if any progress

**Comment by truscellino** [comment]
To add to the confusion, the messages app started to work again today on my OnePlus One... ??? I didn't make any changes, I am still on RC 101... this is very puzzling sorry, doesn't help much in terms of debugging :-S
The Nexus 5 is back to stable channel so I can't add any feedback.
Happy to do a bit of testing with some guidance. Thanks!
