### ISSUE TITLE
RC  copy/paste a message doesn't seem to work in RC channel

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/messaging-app#295]
I just tried and seen this totay with last RC 18 on the Volla. 
It seems impossible to copy a message from messaging-app and to paste it inside an other new message , or outside messaging-app (for example in Teddit).
I don't know on other smartphones but with my BQ E5 HD OTA-17, it works. I don't remember if i tried with OTA-17 on Volla.

**Comment by lduboeuf** [comment]
humm can't reproduce on devel

**Comment by gbdomubpkm** [comment]
Clarification:
In fact, this is not systematic and
it also happens with OTA-17 on the Volla but depending on some pieces of text copied from a webapp that I paste into a message. I then send the message to myself, copy it afterwards and it can't be pasted anywhere.
I'll clarify later if I can figure it out....

**Comment by lduboeuf** [comment]
Yes there are random issue on copy/paste between apps. I use in that case the paste from the keyboard ( long press on the space bar ) as it is always working

**Comment by gbdomubpkm** [comment]
Surely.
But something might be wrong with the clipboard in some circumstances as the paste action from the keyboard didn't work sometimes as if there wasn't a copy of a message (no copy --> no paste).
This doesn't seem to happen on the stable channel now.
Watch for it on the next RC (or DEV).

**Comment by gbdomubpkm** [comment]
digression
After changing from RC to stable, the emoji (smile) remains on the Volla. Is this normal? (not annoying). Not the emoji on BQ E5 HD on OTA-17.
![screenshot20210607_113946334](https://user-images.githubusercontent.com/50362604/120996684-d5b6bc80-c786-11eb-9942-3d9be12b3fee.png)
![screenshot20210607_114004498](https://user-images.githubusercontent.com/50362604/120996689-d6e7e980-c786-11eb-83b5-ed8708843b1f.png)

**Comment by lduboeuf** [comment]
@gbdomubpkm Yes it is normal, in fact the sticker feature was already there if anything found under "sticker" folder, it will not work thought on stable OTA-17

**Comment by gbdomubpkm** [comment]
ok 🙂

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/295

Sorry for your inconvenience.
