### ISSUE TITLE
Sometimes, unable to write a message

### ISSUE THREAD

**Issue by lduboeuf** [ubports/messaging-app#299]
related to issue: ubports/ubuntu-touch#1444

From @Rargente :
I can confirm that this also happens when opening the sms from the indicator bar.

From @gbdomubpkm :
Opening the sms with indicator bar : Yes keyboard not going out is systematic with the Volla. After that, switching to another SMS conversation (other contact) does not make the keyboard go out: the only way to make it go out is to close messaging-app and reopen it.

Reproductible use case:

Start to write a sms, go to cellular settings from the indicator, and go to APN settings-> Acces Point -> Save then go back to messaging-app. The keyboard can't be opened anymore.

**Comment by Danfro** [comment]
I remember that problem when switching to another app and back to messaging app. I tried the steps described above and also tried switching between apps. I can not reproduce the error anymore. Seems to be fixed. :+1: 
Xperia X, devel, 64bit
