### ISSUE TITLE
Demo on message not working anymore

### ISSUE THREAD

**Issue by lduboeuf** [ubports/messaging-app#300]
When on first time run, when in conversation view, the demo does not display animations for swipe actions.

**Comment by Flohack74** [comment]
Can you provide instructions how to manually force the demo to run so testers might repeat that process a few times?

**Comment by lduboeuf** [comment]
To test: edit ~/.config/com.ubuntu.messaging-app/MessagingApp.conf and set hintNecessary to true.
Start the app and then send a new message. 
Or go into an existing conversation ( it may not work in every situation because it relies on message count which may not yet be updated, this should not happen when you start to use the app for the first time )

**Comment by c4pp4** [comment]
RC OTA22: 2022-W04 (device: Mi A2)
Works. I've tried an existing conversation with no result, but after sending a new message, first run demo started.
