### ISSUE TITLE
Feature request, disable keyboard auto pop-up when opening sms

### ISSUE THREAD

**Issue by Litolindo** [ubports/messaging-app#302]
Dear all, 
UT messaging app is beautiful but keyboard destruct reading sms as it pop-up automatically. Maybe we can disable auto pop-up of keyboard when opening and reading sms.

Regards,
Lito

**Comment by lduboeuf** [comment]
Do you know you can dismiss the keyboard by swiping down from the edge ?

**Comment by Litolindo** [comment]
> Do you know you can dismiss the keyboard by swiping down from the edge ?

Yes

**Comment by mateosalta** [comment]
Hi, I believe we change this on purpose, in the old days the text field would not auto focus and users wanted the implementation of immediate less taps response to messages. The current behavior was part of a feature improvement.   As such I don't think we should revert a positive time saving feature for users. 

Perhaps if the opposite is wanted by more it might be implemented as a option in settings?

**Comment by Litolindo** [comment]
> Hi, I believe we change this on purpose, in the old days the text field would not auto focus and users wanted the implementation of immediate less taps response to messages. The current behavior was part of a feature improvement.   As such I don't think we should revert a positive time saving feature for users. 
> 
> Perhaps if the opposite is wanted by more it might be implemented as a option in settings?

Oh I see, so this is already available in those old days. Perhaps we can add this to message app settings to give users an alternate option either to focus in writing sms or focus in reading sms.

**Comment by lduboeuf** [comment]
I see on Teleport, FluffyChat and on other OSes that the keyboard is not shown automatically. That should be something to consider .

**Comment by mateosalta** [comment]
> I see on Teleport, FluffyChat and on other OSes that the keyboard is not shown automatically. That should be something to consider .

perhaps we can only do this when you open from notifications? (url dispatcher) i do like the speed up in usage, but does seem difrent enough that i can see why some like it not showing
