### ISSUE TITLE
Frequent crash on startup

### ISSUE THREAD

**Issue by mardy** [ubports/messaging-app#309]
I'm quite puzzled that no one else seems to be affected by this, but the application often (80% of the times) crashes for me on startup or (less frequently) when pulling up the composition panel from the bottom of the screen.

Those times when it doesn't crash at startup, it crashes at termination or, when it doesn't even there, it prints the following message:
```
"There are still \"1\" items in the process of being created at engine destruction."
```

I could never reproduce the crash when running the application under `strace`, but I could reproduce it with `gdb`, and the backtraces were different: for instance, [this](https://pastebin.com/i9NUxhwW) and [this](https://pastebin.com/KtrJGUQv). The only thing that never changed, was that the crash always involved the QML incubator.

I had a look at the Qt bug reports, and found several bugs which could be related, including [this one](https://bugreports.qt.io/browse/QTBUG-30928) that was actually filed for UT. One bug that looked especially interesting was this one, which is still open for Qt 5.12: https://bugreports.qt.io/browse/QTBUG-84914

That also helped in finding a workaround (see the PR I'm going to link soon).

The last question is why I seem to be the only one having experienced this bug. I believe that it's due to the device CPU speed, as I've been hitting this on `violet`, which is a relatively powerful device. I did not reproduce this on other devices. For the record, I'm using devel image 20210826-8261.

**Comment by lduboeuf** [comment]
@mardy I rather have app stuck on logo at start up sometimes ( but could be my setup ). Do you have lots of theads/messages ?

**Comment by mardy** [comment]
> @mardy I rather have app stuck on logo at start up sometimes ( but could be my setup ). Do you have lots of theads/messages ?

No, quite the opposite: just two threads.

**Comment by Fuseteam** [comment]
it indeed does not seem to crash as much anymore, i have yet to see it crash; which is a good thing

**Comment by ivoxavier** [comment]
Hi,

To test this I took two phones one the devel channel (FP2) and other with OTA-20 (H9 device 6T). 

Lucky or not, once I start the Messaging App on the OTA-20 and swiped up to write an new message and closing again, when trying to open the App again it stayed on the splash screen for ever. Attempted the same exercise on the devel channel and no problem, everything worked as expected.

So far, not a single crash at Message App on devel channel image (2021-12-06) for FP2.
