### ISSUE TITLE
Notifications/unread bug

### ISSUE THREAD

**Issue by konradybcio** [ubports/messaging-app#31]
Not sure if I'm supposed to put that there or in indicator-messages, but from what I noticed when you recieve a text and click the little icon on the notification bar to open in app, when you go back into the app the message is still marked as unread.

**Comment by ChristianPauly** [comment]
I can confirm this. I have this bug in the chat with my mother but only with her. Every time I open the app it feels like I've been naughty...

**Comment by userj** [comment]
It happens every time. There doesn't seem to be communication between the notification bar and messaging-app with regards to read messages. Even when you open the app it jumps up to the first "unread" message.

**Comment by Thieb67k** [comment]
I frequently have the same problem.
(LGE Nexus 4, OTA-5-9)

**Comment by lduboeuf** [comment]
still happening ? I don't reproduce on my N5

**Comment by james-lyon** [comment]
This still happens to me very often (Aquaris E4.5 on Stable)

**Comment by lduboeuf** [comment]
maybe a bad record somewhere. Can you provide logs ? /home/phablet/.cache/upstart/application-legacy-messaging-app-.log

**Comment by james-lyon** [comment]
[application-legacy-messaging-app-.log](https://github.com/ubports/messaging-app/files/3922708/application-legacy-messaging-app-.log)

Here you go, I've removed some information (phone numbers, message text etc.)

**Comment by lduboeuf** [comment]
humm,  are you using dual sim ?
To make sure it can be that part, you can test with only one card inserted .
More tests:
if messaging-app is already open, do you have the same issue.
If it can come from a corrupted database, you can backup and remove `/home/phablet/.local/share/history-service/history.sqlite` ( better not to have the app open ) and see if it happen again.

**Comment by james-lyon** [comment]
I am using dual sim, and in the settings I have messages set to "Ask me each time". I'll also do a test with setting one of the sims to default.

**Comment by lduboeuf** [comment]
Is someone still experiencing that ?

**Comment by Thieb67k** [comment]
From my side, that looks ok.
Thanks for the job!

**Comment by lduboeuf** [comment]
ok, i close that issue for now, thx
