### ISSUE TITLE
images are cropped and not easily readable

### ISSUE THREAD

**Issue by lduboeuf** [ubports/messaging-app#318]
![screenshot20211230_160818965](https://user-images.githubusercontent.com/11663835/147764529-7b1a17a5-6498-43a1-83de-ddae05e8e9ca.png)

**Comment by lduboeuf** [comment]
For test: Send and/or receive images from MMS. They should be now not cropped

**Comment by stefan-kalb** [comment]
send and receive successfully tested. No cropping.

**Comment by rik-shaw** [comment]
@lduboeuf sorry I was away for a bit so couldn't give feedback on this one. Good to see it solved and confirmed, but I am slightly confused by the old situation: was it only cropping in the "message chat view" or was it truly cropped (meaning if you click to open the image was it cropped there)? Thanks for any clarification.

**Comment by lduboeuf** [comment]
@rik-shaw only cropped in the conversation view as shown above

**Comment by rik-shaw** [comment]
> @rik-shaw only cropped in the conversation view as shown above

Ahh ok, thanks I can confirm the bug before and the fix now :-) I considered it a "weakness not a bug" before, it kept the message list tidy with like-sized photos but yes a bit annoying so preferable with the fix to show full image dimension. Thanks again!
