### ISSUE TITLE
feature request: put a timed undo delete button to prevent people from deleting all messages of a one contact by accident

### ISSUE THREAD

**Issue by matzgewinn** [ubports/messaging-app#321]
Like in the "Dekko"-app I suggest putting in a timed undo button in the messaging-app of ubuntu touch. Some silly people like me sometimes swipe by accidentone of their contacts to the right and then press the delete-button. If there were an undo button ore a question like: do you really want to delete the messaging history of this contackt? this might be very helpful.

**Comment by matzgewinn** [comment]
thanks a lot to my heroes! :-)

**Comment by lduboeuf** [comment]
@matzgewinn note that due to display issues, we've implented a classic popup confirm.
Hope it wlill be fine.
And i think it is more consistant with other core apps

**Comment by luksus42** [comment]
Works and is very useful ;-).
