### ISSUE TITLE
Messaging not saving/downloading pictures in any format (.jpg)

### ISSUE THREAD

**Issue by ronbillock** [ubports/messaging-app#323]
My wife and I both are now on OP6 trying to make it our daily driver. Today my wife received multiple pictures in a message. We opened each picture and did a download to the Pictures folder where it then syncs to our NextCloud. After the Sync, the NC Picture folder showed multiple gray file icons with a single-digit number for a name, i.e. 3,4,7. They would not open. I looked in the file folder on the phone and the pictures were there and they did download from Messages, though that is a multi-step manual process. The phone Picture folder showed a mini pic vs a grayed icon like on NC. What I noticed is the file name in the file Pictures folder on the phone was also just a single-digit number like 3,4,7. There were no .jpg in the names. I had to do a 'Rename' and add .jpg for each one, perform a re-sync, and then everything was fine in NC. I was then able to open the files on NC because it recognized the file format. Seems like a bug to me?

**Comment by lduboeuf** [comment]
Sorry, i've just discovered the ticket. 
I've just tested today, and confirmed that pictures are stored 1,2,3 etc...
idk if its a bug or it has always be like that.

**Comment by lduboeuf** [comment]
Confirmed, but this have always be the case

**Comment by ronbillock** [comment]
Still seems to be a bug regardless. This seems different from the other problems with the UT Messenger APP regarding MMS and Group Messaging. Messaging is a fundamental app for mobile users.

**Comment by lduboeuf** [comment]
> Messaging is a fundamental app for mobile users.

No need to say that, i know it , and already took several days/weeks freely to improve it ;-)

**Comment by lduboeuf** [comment]
This should correct that issue, but only on new sent, received images
https://gitlab.com/ubports/core/history-service/-/merge_requests/15

**Comment by lduboeuf** [comment]
Part of the work is also here for outgoing MMS:
https://github.com/ubports/telephony-service/pull/56

**Comment by lduboeuf** [comment]
@Flohack74 can it also be on OTA-24 Board ? MR ready : https://gitlab.com/ubports/core/history-service/-/merge_requests/15

**Comment by Flohack74** [comment]
It is now ;)

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/318

Sorry for your inconvenience.
