### ISSUE TITLE
handle sms:// url scheme

### ISSUE THREAD

**Issue by lduboeuf** [ubports/messaging-app#344]
Some websites have a link to create a sms with sms:// url scheme

Tests can be done with https://bradorego.com/test/sms.html
( Note that all example will not work as url-dispatcher will not handle them

**Comment by Danfro** [comment]
Xperia X, RC.

When clicking on the links provided on that webpage messaging app is opened and a number is entered and edit mode for a new message is active. I guess that is a success. 👍 

This does work when messaging app is closed and when it is open.

**Comment by ilyakooo0** [comment]
From the link I tested the first four links. They all open the "new  sms message" screen correctly, however the message body doesn't seem to be properly handled.

### Results

sms:5552345678
<img src="https://user-images.githubusercontent.com/6209627/202752148-e800ffdc-82dd-4a52-89ed-d2b0e143f44e.png" width="250px"/>


sms:+15552345678
<img src="https://user-images.githubusercontent.com/6209627/202752156-5812bdac-53e7-4566-8a0f-fe38aba61f6f.png" width="250px"/>


sms:?body=Hello,%20world
<img src="https://user-images.githubusercontent.com/6209627/202752102-4e788e3a-a10d-4903-b4a6-a814b16f443e.png" width="250px"/>

sms:;body=Hello,%20world
<img src="https://user-images.githubusercontent.com/6209627/202752168-9579a029-4cba-433e-8df2-ccbe5cc1a860.png" width="250px"/>

**Comment by lduboeuf** [comment]
@ilyakooo0 oh true, there has been a missing code somewhere, i will have a look on next OTA and maybe gone with the contact revert i can't remember

**Comment by ivoxavier** [comment]
Tested in FP4 and 6T and got the same results ilyakooo0. 
So, for me is 👍
