### ISSUE TITLE
Links in SMS contain extra amp; in url

### ISSUE THREAD

**Issue by jmlich** [ubports/messaging-app#355]
I have received SMS text message containing URL. After clicking to the URL the web browser was opened on different URL. It seems, the `&` symbol was transformed to `&amp;` string. 

For example:

- The URL is the message was `https://erpid.info/erp?i=SOMETOKEN8&s=10.10.2022`
- The URL in web browser was `https://erpid.info/erp?i=SOMETOKEN8&amp;s=10.10.2022`
- The link seems to be transformed to `<a href="https://erpid.info/erp?i=SOMETOKEN8&amp;s=10.10.2022">https://erpid.info/erp?i=SOMETOKEN8&s=10.10.2022</a>`

I am not sure, but it seems the link is formatted here https://github.com/ubports/messaging-app/blob/xenial/src/qml/MessageBubble.qml#L71

**Comment by lduboeuf** [comment]
> * &amp;

`&amp;` is valid in an url, does it cause any issue ?

**Comment by jmlich** [comment]
The result is that browser opens different URL than expected. It looks like the `&` is transformed into `&amp;` when it shouldn't.

It is even possible that `&` sign is expanded twice:
```
<a href="https://erpid.info/erp?i=SOMETOKEN8&amp;amp;s=10.10.2022">https://erpid.info/erp?i=SOMETOKEN8&s=10.10.2022</a>
```

**Comment by lduboeuf** [comment]
i see ok

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/320

Sorry for your inconvenience.
