### ISSUE TITLE
Show on which number an SMS has been received

### ISSUE THREAD

**Issue by alexanderisme** [ubports/messaging-app#4]
Go to a message in the messaging app, swipe to the side and click on the "i" to get the details of the message. The second information is "from" (I think so, I'm translating the "de" of the french) and the third is "to" (="à"). 
If you have sent the message: in the 2nd information you see "yourself" (=Moi-même)
If you received the message: in the 3rd information you see "yourself"
What I expect to see: a phone number!
I think that's important, because the phone I'm using (BQ E4.5) is double SIM and it's important to know with which SIM I have sent the message because I have two different numbers. In addition if you change the SIM card it's still yourself, but it's not the same phone number!
I don't know if it's really interesting to know in this information list if it's yourself that wrote the message, since to accede to the list you have to see the message and there is a color code (green for written messages, white for received messages)

**Comment by Flaburgan** [comment]
Can this be renamed to "Show on which number I received a SMS" please? It would be easier to know what this is about.

**Comment by lduboeuf** [comment]
@Flaburgan , @alexanderisme  or others, can you please test that PR as i don't have dual sim :) : https://github.com/ubports/messaging-app/pull/162
`sudo upbports-qa install PR-162`

**Comment by Danfro** [comment]
Nice one. Works fine on E5, devel.

**Comment by Danfro** [comment]
It does work fine on my Xperia running devel. 
Next to the time when an sms was received, I do get @SIM 1 whateveritisnamed.
