### ISSUE TITLE
[xenial] Contacts are missing in messaging app

### ISSUE THREAD

**Issue by advocatux** [ubports/messaging-app#40]
**Devices:** 
* Nexus 5 (hammerhead) - Ubuntu 16.04 (2018-09-02/2)
* BQ E4.5 (krillin)  - Ubuntu 16.04 (2018-09-02)

**Channel:** devel

**Steps to reproduce:**
- Open messaging-app to send an SMS.
- Press the `+` sign to search for contacts
- It can't find the contacts and this screen shows:
![nocontactsinmessapp](https://user-images.githubusercontent.com/30233652/44959082-9e39c800-aee9-11e8-8135-f03efa4fd8e7.jpg)

**Logs:**
- hammerhead https://paste.ubuntu.com/p/Bx7Ybv3Zsb/
- krillin https://paste.ubuntu.com/p/PXMHQCYB6y/

**Comment by UniversalSuperBox** [comment]
Is this still a problem?

**Comment by advocatux** [comment]
No, it isn't. I close the issue.
