### ISSUE TITLE
The last message of a conversion shall be displayed in two lines in the conversation preview.

### ISSUE THREAD

**Issue by Benni777** [ubports/messaging-app#46]
Environment:
- Nexus 4 (mako), 16 GB
- Ubuntu 16.04 (2018-09-17)
- Channel: dev

Steps:

1. Open Messages

Actual:
- Conversations are displayed sorted by contact and date
- For each conversation the first around **40** characters of the last message are displayed in one line and cut with "...".

Feature request:
-  Conversations are displayed sorted by contact and date
- For each conversation the first around **80** characters of the last message are displayed in **two** lines and cut with "...".

**Comment by JulienPeloton** [comment]
Environment:
* Device: Nexus 5
* channel: rc
* Build: Ubuntu 16.04 (2019-W18)

It works as expected! Thanks.

**Comment by jezek** [comment]
FP2 (2019-W18)
Conversation preview of long last message has two lines, cut with "..."

**Comment by ziggutas** [comment]
BQ E4.5 rc (2019-W18)
Two lines displayed in both landscape and portrait. More characters shown in landscape.
