### ISSUE TITLE
Input field is not aligned correctly

### ISSUE THREAD

**Issue by Benni777** [ubports/messaging-app#47]
Environment
- Nexus 4 (mako), 16 GB
- OS: Ubuntu 16.04 (2018-09-17)
- Channel: dev

Steps
1. Open Messages
2. Touch + to add new conversion

Expected
- Input field on the top is exactly in the center.

Actual
- Input field on the top is not exactly in the center. It is a bit too far left.

**Comment by Danfro** [comment]
I do not exactly remember how it was before :smirk:  but it does look pretty cool and centred now on my E5 RC 2019-W18. :+1:

**Comment by jezek** [comment]
FP2 (2019-W18)
Top input field is in the center in portrait & lanescape mode.

**Comment by ziggutas** [comment]
BQ E4.5 rc (2019-W18)
Input field is central

**Comment by ziggutas** [comment]
Nexus 7 (flo) rc (2019-W18)
Input field is central
