### ISSUE TITLE
Messaging app freeze

### ISSUE THREAD

**Issue by mbarhon** [ubports/messaging-app#5]
Helo all.

I experience problem with messaging app on my BQ aquaris 4.5 (build ubuntu15.04-armf 20170610)
When you have lot of messages and want delete some of them the app freeze and then you are not able to start the app again until you restart whole device. I have to say that is little annoying.

**Comment by lduboeuf** [comment]
Hello, are you still experiencing that ?

**Comment by lduboeuf** [comment]
I guess, we can close that issue for now
