### ISSUE TITLE
[OTA-5] Clicking on contact logo in a chat breaks the app

### ISSUE THREAD

**Issue by ChristianPauly** [ubports/messaging-app#50]
After updating to OTA-5 (via UBports installer) I've got this after clicking the contact icon top right in the chat page:

![pwjownbepzliomogcmtbtlwb](https://user-images.githubusercontent.com/24619905/46932224-f9192000-d04e-11e8-91ec-fcd360d48fb4.png)

**Comment by kugiigi** [comment]
This also happens when doing the following:
1. Create new message by swiping from the bottom or tapping the + button.
2. In the recipient field, tap the + button to select contacts.
3. Tap any of your contacts.

Same result as the screenshot shown in the first post.

**Comment by UniversalSuperBox** [comment]
@mardy is this also related to the changes in QtPIM?

**Comment by kugiigi** [comment]
I found the culprit.
Apparently `ContactViewPage `does not support `leadingActions `anymore.
I can't find `ContactViewPage ` though so I cannot confirm.
But it looks like I can just remove the code because it's for the back button which I think unnecessary.
Could be a remnant of the old versions of UITK?

```
leadingActions: [
        Action {
            objectName: "cancel"

            text: i18n.tr("Cancel")
            iconName: "back"
            shortcut: "Esc"
            onTriggered: pageStack.removePages(root)
        }

    ]
```

**Comment by Flohack74** [comment]
Please make a test build, and then a pull request, yes. Mention in the pull request "fixes #50" in the description :)

**Comment by kugiigi** [comment]
Can you please check why the commit that fixed this isn't on devel? Perhaps xenial is the wrong branch to do the PR? I've checked in latest devel and the code I removed is still there.

**Comment by UniversalSuperBox** [comment]
Fixed with the merge of https://github.com/ubports/messaging-app/pull/63.

To test:
1. Open Messaging
1. Open any chat
1. Tap the Contact icon in the top actions bar

**Comment by tjrhodes** [comment]
device: Fairphone 2
channel: RC 2018-W48
issue solved. No noticeable side effects

**Comment by pbonnell** [comment]
device: Nexus 5
channel: RC 2018-W48
issue solved. No noticeable side effects
