### ISSUE TITLE
Add account button let me do nothing

### ISSUE THREAD

**Issue by ChristianPauly** [ubports/messaging-app#51]
In OTA-5 there is the new button "Add an online account" in the settings. But it let me do nothing. Maybe it is meant for future features, which would be great. But I would recommend to hide the button until the feature is ready.

![screenshot20181015_075232296](https://user-images.githubusercontent.com/24619905/46932398-d63b3b80-d04f-11e8-8bde-0b2ef2d02262.png)

**Comment by Danfro** [comment]
Ota-8 still the same :-)
