### ISSUE TITLE
CMake does not update the .pot file

### ISSUE THREAD

**Issue by ChristianPauly** [ubports/messaging-app#52]
A lot of new strings are not translated. It looks like the .pot file haven't been updated.

**Comment by Danfro** [comment]
I didn't know that the pot file needs to be updated with the PR as well. I thought that was done with the build and then transferred to weblate. I will remember that. PR/MR should not be merged without the pot file then maybe?

Just spotted, that the new settingspage does contains mostly untranslated strings. Other apps do have the same problem. Maybe that information needs to be spread/repeated to everyone developing?

**Comment by krille-chan** [comment]
It looks like there is a problem with cmake. The .pot file hasnt got an update since 2016-07-21...

The cmake file in po/CMakeLists.txt is executed every time but it does not update the .pot file.

**Comment by Danfro** [comment]
So does that mean the .pot file is updated via script? So do translators have to commit the pot file as @Flohack74 said "last year"? Or is that information maybe outdated? Or am I mixing up things?
