### ISSUE TITLE
Text not writable in Window Mode

### ISSUE THREAD

**Issue by PetHH** [ubports/messaging-app#6]
On my OPO in "Window" Usage Mode i can either type Text on the On-Screen Keyboard, or watch what i have typed in getting the App Window to the front. 
i can't see both, because the Keyboard popping on is not aligning the App-Window to a smaller size, to watch both, Keyboard and and written Text-line as it does in "Stage" Modus. 
That is true for horizontal and vertical rotate. 

Is there an unknown (for me)  trick ?

**Comment by lduboeuf** [comment]
hello, is this issue still happening ? Don't get what "Window" mode means. Are you using an external display ?

**Comment by PetHH** [comment]
hi, i'm not using ubport anymore, because i find it it rather stupid to 
disable the 'hardware' buttons down under the display of my mobile 
'menu' 'home' and 'back' , just to fullfill the name of ubTOUCH' , so 
they better take an immense time of programming the system menu's just 
to add this "features menu, home, back" functions to the screen, just to 
follow the demand to do everything by "touch" , and it still doesn't 
work at every point.

Am 10.01.20 um 23:05 schrieb Lionel Duboeuf:

**Comment by lduboeuf** [comment]
fine, that's your personal opinion. Sometimes hard to change habits. I've never used Android as a daily basis, so i can't tell. I've never missed the back, home, menu button :)
