### ISSUE TITLE
no draft in SMS App

### ISSUE THREAD

**Issue by Thieb67k** [ubports/messaging-app#65]
Description of the feature
A draft would be very welcome when writing a text in SMS App.

- Device: LGE Nexus 4
- Channel: Stable
- Build: OTA-5

Steps to reproduce
When you write a SMS, apparently there is no possibility to save it. If you leave the App for whatever reason and go back, the text disappear.

Expected behavior
The possibility to find the text after a while if you leave the App would be a good option.

Actual behavior
Currently I have to write the text from the beginning...

**Comment by Thieb67k** [comment]
That bug or oversight still happens with OTA-6 on LGE Nexus 4.

**Comment by Scym1** [comment]
I guess this fix just hit RC because I have a new bug related to this. Now, the SMS input box doesn't empty itself after sending an SMS.

I thought I didn't send the message so I hit send again.. I sent the same SMS twice and even thrice on one occasion in less than 2 seconds.

I have to erase my last message before typing a new one every time.

Otherwise, the draft is saved even if I close the app. That's nice. :) I just don't want it saved when it's sent. :P

I'm on Nexus 5, RC channel.

**Comment by UniversalSuperBox** [comment]
Hello @Scym1,

Please see https://github.com/ubports/messaging-app/issues/108, which was fixed and will be in the next RC.

**Comment by jezek** [comment]
FP2 (2019-W32) - Fixed. Unfinished (unsent) text is not discarded after app shutdown or leaving conversation. After revisiting conversation the unfinished text is there and can be continued.

**Comment by Thieb67k** [comment]
Hello,
That OTA-10 update I was waiting for is not working for me. I still have no draft...
I tried in differents ways, reboot... no draft.
:(
There is just to write, quit and going back right?

**Comment by jezek** [comment]
@Thieb67k 
> There is just to write, quit and going back right?

Here is how it works for me. Open app, open conversation, write something (eg. "test"), close app (don't send). Reopen, and after tapping the same conversation, there is the previous message.

FP2 (2019-W33/2)

**Comment by Thieb67k** [comment]
Thanks for your answer.
I got it. That is super nice. We just have to use the arrow on the top-left corner before closing the app.
If I bypass the arrow and close the app, the text is erased.

But, would it be nice to allow users to create a draft without pre-existing conversation? And the possibility to have the "To:" field empty, in the aim to complete it afterwards?
Because sometimes I want to prepare a text and sent it several hours later (when I prepare an event) and now I do not have possibility to intercalate a text between an opened conversation and a draft.

So far, I should open a conversation with myself then copy/paste or forward the text to the complete list of adressees just before sending.

I hope I am clear... 
Anyway, thanks for the job!

**Comment by jezek** [comment]
@Thieb67k 
> We just have to use the arrow on the top-left corner before closing the app.
If I bypass the arrow and close the app, the text is erased.

For existing conversations, it works for me also without using the "back" (top-left corner) arrow.
