### ISSUE TITLE
Add an option to use the system theme

### ISSUE THREAD

**Issue by hummlbach** [ubports/messaging-app#89]
It would be cool to have the option to use the system theme.
Instead of using a slider button to switch between light and dark theme, an ExpandableListItem with the options Light, Dark and System could be used. (Already done here: https://gitlab.com/ubports/apps/clock-app/blob/master/app/alarm/AlarmSettingsPage.qml#L227 but unfortunately the clock doesn't know how to query available themes.)

**Comment by krille-chan** [comment]
Shouldn't we just remove the feature to set a custom theme? When there is a global setting for the dark mode, do all apps need their own switch to ignore this theme?

**Comment by UniversalSuperBox** [comment]
No, it is very possible that a user would want one or a few apps to be a certain theme all the time. Unless the option gets in the way of other changes, I'd call it an accessibility feature and leave it there.
