### ISSUE TITLE
Unable to open new sms when already inn app as message arrives 

### ISSUE THREAD

**Issue by abkro** [ubports/messaging-app#96]
Device: LGE Nexus 5
Release: 2019-W18

Expected behavior: When you have the message app open in the main view with all message threads, and a new message is received, you should be able to select the thread in question and be taken directly to the new message.

Actual behavior: Selecting the thread with the new message does not work. Selecting the message thread from the notification does not work either. You have to close the app and reopen it in order to enter the message thread in question.

It is possible to reply to the message from the notification quick reply option, but  not possible to enter the thread itself without closing the app first.

**Comment by lduboeuf** [comment]
I don't reproduce that currently on N5 devel. @abkro still happening for you ?

**Comment by lduboeuf** [comment]
can we close that issue for now ? 
 @Flohack74
